/**
	* \file VecBrlyVJob.cpp
	* vector VecBrlyVJob (implementation)
	* \copyright (C) 2016-2020 MPSI Technologies GmbH
	* \author Alexander Wirthmueller (auto-generation)
	* \date created: 11 Jan 2021
  */
// IP header --- ABOVE

#include "VecBrlyVJob.h"

using namespace std;
using namespace Sbecore;
using namespace Xmlio;

/******************************************************************************
 namespace VecBrlyVJob
 ******************************************************************************/

uint VecBrlyVJob::getIx(
			const string& sref
		) {
	string s = StrMod::lc(sref);

	if (s == "crdbrlycon") return CRDBRLYCON;
	if (s == "crdbrlyfil") return CRDBRLYFIL;
	if (s == "crdbrlyflt") return CRDBRLYFLT;
	if (s == "crdbrlyleg") return CRDBRLYLEG;
	if (s == "crdbrlyloc") return CRDBRLYLOC;
	if (s == "crdbrlynav") return CRDBRLYNAV;
	if (s == "crdbrlyopr") return CRDBRLYOPR;
	if (s == "crdbrlyprs") return CRDBRLYPRS;
	if (s == "crdbrlypty") return CRDBRLYPTY;
	if (s == "crdbrlyreg") return CRDBRLYREG;
	if (s == "crdbrlyrly") return CRDBRLYRLY;
	if (s == "crdbrlyseg") return CRDBRLYSEG;
	if (s == "crdbrlyttb") return CRDBRLYTTB;
	if (s == "crdbrlyusg") return CRDBRLYUSG;
	if (s == "crdbrlyusr") return CRDBRLYUSR;
	if (s == "dlgbrlyconnew") return DLGBRLYCONNEW;
	if (s == "dlgbrlylegnew") return DLGBRLYLEGNEW;
	if (s == "dlgbrlynavloaini") return DLGBRLYNAVLOAINI;
	if (s == "dlgbrlyttbimpflt") return DLGBRLYTTBIMPFLT;
	if (s == "dlgbrlyttbnew") return DLGBRLYTTBNEW;
	if (s == "dlgbrlyttbtrlorig") return DLGBRLYTTBTRLORIG;
	if (s == "jobbrlyiexflt") return JOBBRLYIEXFLT;
	if (s == "jobbrlyiexini") return JOBBRLYIEXINI;
	if (s == "jobbrlyiexttb") return JOBBRLYIEXTTB;
	if (s == "pnlbrlycon1nrelay") return PNLBRLYCON1NRELAY;
	if (s == "pnlbrlyconconmnequipment") return PNLBRLYCONCONMNEQUIPMENT;
	if (s == "pnlbrlycondetail") return PNLBRLYCONDETAIL;
	if (s == "pnlbrlyconheadbar") return PNLBRLYCONHEADBAR;
	if (s == "pnlbrlyconlist") return PNLBRLYCONLIST;
	if (s == "pnlbrlyconmap") return PNLBRLYCONMAP;
	if (s == "pnlbrlyconmnflight") return PNLBRLYCONMNFLIGHT;
	if (s == "pnlbrlyconmnsegment") return PNLBRLYCONMNSEGMENT;
	if (s == "pnlbrlyconpre") return PNLBRLYCONPRE;
	if (s == "pnlbrlyconrec") return PNLBRLYCONREC;
	if (s == "pnlbrlyconref1nsegment") return PNLBRLYCONREF1NSEGMENT;
	if (s == "pnlbrlyfildetail") return PNLBRLYFILDETAIL;
	if (s == "pnlbrlyfilheadbar") return PNLBRLYFILHEADBAR;
	if (s == "pnlbrlyfillist") return PNLBRLYFILLIST;
	if (s == "pnlbrlyfilrec") return PNLBRLYFILREC;
	if (s == "pnlbrlyflt1nconnection") return PNLBRLYFLT1NCONNECTION;
	if (s == "pnlbrlyfltdetail") return PNLBRLYFLTDETAIL;
	if (s == "pnlbrlyflteqp1nnode") return PNLBRLYFLTEQP1NNODE;
	if (s == "pnlbrlyflteqpmnconnection") return PNLBRLYFLTEQPMNCONNECTION;
	if (s == "pnlbrlyfltfafawaypoint") return PNLBRLYFLTFAFAWAYPOINT;
	if (s == "pnlbrlyfltheadbar") return PNLBRLYFLTHEADBAR;
	if (s == "pnlbrlyfltlist") return PNLBRLYFLTLIST;
	if (s == "pnlbrlyfltmnconnection") return PNLBRLYFLTMNCONNECTION;
	if (s == "pnlbrlyfltmnlocation") return PNLBRLYFLTMNLOCATION;
	if (s == "pnlbrlyfltorgmnflight") return PNLBRLYFLTORGMNFLIGHT;
	if (s == "pnlbrlyfltpre") return PNLBRLYFLTPRE;
	if (s == "pnlbrlyfltrec") return PNLBRLYFLTREC;
	if (s == "pnlbrlyfltref1nsegment") return PNLBRLYFLTREF1NSEGMENT;
	if (s == "pnlbrlyleg1nflight") return PNLBRLYLEG1NFLIGHT;
	if (s == "pnlbrlylegcor1nconnection") return PNLBRLYLEGCOR1NCONNECTION;
	if (s == "pnlbrlylegdetail") return PNLBRLYLEGDETAIL;
	if (s == "pnlbrlylegheadbar") return PNLBRLYLEGHEADBAR;
	if (s == "pnlbrlyleglist") return PNLBRLYLEGLIST;
	if (s == "pnlbrlylegmap") return PNLBRLYLEGMAP;
	if (s == "pnlbrlylegmnlocation") return PNLBRLYLEGMNLOCATION;
	if (s == "pnlbrlylegorgmnleg") return PNLBRLYLEGORGMNLEG;
	if (s == "pnlbrlylegpre") return PNLBRLYLEGPRE;
	if (s == "pnlbrlylegrec") return PNLBRLYLEGREC;
	if (s == "pnlbrlylocbgn1nleg") return PNLBRLYLOCBGN1NLEG;
	if (s == "pnlbrlylocdetail") return PNLBRLYLOCDETAIL;
	if (s == "pnlbrlylocend1nleg") return PNLBRLYLOCEND1NLEG;
	if (s == "pnlbrlyloceqp1nnode") return PNLBRLYLOCEQP1NNODE;
	if (s == "pnlbrlyloceqpmnconnection") return PNLBRLYLOCEQPMNCONNECTION;
	if (s == "pnlbrlylocheadbar") return PNLBRLYLOCHEADBAR;
	if (s == "pnlbrlyloclist") return PNLBRLYLOCLIST;
	if (s == "pnlbrlylocmap") return PNLBRLYLOCMAP;
	if (s == "pnlbrlylocmnflight") return PNLBRLYLOCMNFLIGHT;
	if (s == "pnlbrlylocmnleg") return PNLBRLYLOCMNLEG;
	if (s == "pnlbrlylocmnsegment") return PNLBRLYLOCMNSEGMENT;
	if (s == "pnlbrlylocproxorgmnlocation") return PNLBRLYLOCPROXORGMNLOCATION;
	if (s == "pnlbrlylocrec") return PNLBRLYLOCREC;
	if (s == "pnlbrlylocvisorgmnlocation") return PNLBRLYLOCVISORGMNLOCATION;
	if (s == "pnlbrlynavadmin") return PNLBRLYNAVADMIN;
	if (s == "pnlbrlynavbase") return PNLBRLYNAVBASE;
	if (s == "pnlbrlynavconnect") return PNLBRLYNAVCONNECT;
	if (s == "pnlbrlynavheadbar") return PNLBRLYNAVHEADBAR;
	if (s == "pnlbrlyopr1nequipment") return PNLBRLYOPR1NEQUIPMENT;
	if (s == "pnlbrlyoprdetail") return PNLBRLYOPRDETAIL;
	if (s == "pnlbrlyoprheadbar") return PNLBRLYOPRHEADBAR;
	if (s == "pnlbrlyoprlist") return PNLBRLYOPRLIST;
	if (s == "pnlbrlyoprrec") return PNLBRLYOPRREC;
	if (s == "pnlbrlyprsadetail") return PNLBRLYPRSADETAIL;
	if (s == "pnlbrlyprsdetail") return PNLBRLYPRSDETAIL;
	if (s == "pnlbrlyprsheadbar") return PNLBRLYPRSHEADBAR;
	if (s == "pnlbrlyprslist") return PNLBRLYPRSLIST;
	if (s == "pnlbrlyprsrec") return PNLBRLYPRSREC;
	if (s == "pnlbrlypty1nequipment") return PNLBRLYPTY1NEQUIPMENT;
	if (s == "pnlbrlyptydetail") return PNLBRLYPTYDETAIL;
	if (s == "pnlbrlyptyheadbar") return PNLBRLYPTYHEADBAR;
	if (s == "pnlbrlyptylist") return PNLBRLYPTYLIST;
	if (s == "pnlbrlyptyrec") return PNLBRLYPTYREC;
	if (s == "pnlbrlyreg1nlocation") return PNLBRLYREG1NLOCATION;
	if (s == "pnlbrlyregadstswitch") return PNLBRLYREGADSTSWITCH;
	if (s == "pnlbrlyregdetail") return PNLBRLYREGDETAIL;
	if (s == "pnlbrlyregheadbar") return PNLBRLYREGHEADBAR;
	if (s == "pnlbrlyreglist") return PNLBRLYREGLIST;
	if (s == "pnlbrlyregrec") return PNLBRLYREGREC;
	if (s == "pnlbrlyregsup1nregion") return PNLBRLYREGSUP1NREGION;
	if (s == "pnlbrlyrly1nnode") return PNLBRLYRLY1NNODE;
	if (s == "pnlbrlyrlydetail") return PNLBRLYRLYDETAIL;
	if (s == "pnlbrlyrlyheadbar") return PNLBRLYRLYHEADBAR;
	if (s == "pnlbrlyrlylist") return PNLBRLYRLYLIST;
	if (s == "pnlbrlyrlyrec") return PNLBRLYRLYREC;
	if (s == "pnlbrlysegdetail") return PNLBRLYSEGDETAIL;
	if (s == "pnlbrlysegheadbar") return PNLBRLYSEGHEADBAR;
	if (s == "pnlbrlyseglist") return PNLBRLYSEGLIST;
	if (s == "pnlbrlysegmnconnection") return PNLBRLYSEGMNCONNECTION;
	if (s == "pnlbrlysegmnlocation") return PNLBRLYSEGMNLOCATION;
	if (s == "pnlbrlysegorgmnsegment") return PNLBRLYSEGORGMNSEGMENT;
	if (s == "pnlbrlysegpre") return PNLBRLYSEGPRE;
	if (s == "pnlbrlysegrec") return PNLBRLYSEGREC;
	if (s == "pnlbrlyttb1nflight") return PNLBRLYTTB1NFLIGHT;
	if (s == "pnlbrlyttbdetail") return PNLBRLYTTBDETAIL;
	if (s == "pnlbrlyttbheadbar") return PNLBRLYTTBHEADBAR;
	if (s == "pnlbrlyttblist") return PNLBRLYTTBLIST;
	if (s == "pnlbrlyttbrec") return PNLBRLYTTBREC;
	if (s == "pnlbrlyttbref1nfile") return PNLBRLYTTBREF1NFILE;
	if (s == "pnlbrlyusgaaccess") return PNLBRLYUSGAACCESS;
	if (s == "pnlbrlyusgdetail") return PNLBRLYUSGDETAIL;
	if (s == "pnlbrlyusgheadbar") return PNLBRLYUSGHEADBAR;
	if (s == "pnlbrlyusglist") return PNLBRLYUSGLIST;
	if (s == "pnlbrlyusgmnuser") return PNLBRLYUSGMNUSER;
	if (s == "pnlbrlyusgrec") return PNLBRLYUSGREC;
	if (s == "pnlbrlyusr1nsession") return PNLBRLYUSR1NSESSION;
	if (s == "pnlbrlyusraaccess") return PNLBRLYUSRAACCESS;
	if (s == "pnlbrlyusrdetail") return PNLBRLYUSRDETAIL;
	if (s == "pnlbrlyusrheadbar") return PNLBRLYUSRHEADBAR;
	if (s == "pnlbrlyusrlist") return PNLBRLYUSRLIST;
	if (s == "pnlbrlyusrmnusergroup") return PNLBRLYUSRMNUSERGROUP;
	if (s == "pnlbrlyusrrec") return PNLBRLYUSRREC;
	if (s == "qrybrlycon1nrelay") return QRYBRLYCON1NRELAY;
	if (s == "qrybrlyconconmnequipment") return QRYBRLYCONCONMNEQUIPMENT;
	if (s == "qrybrlyconlist") return QRYBRLYCONLIST;
	if (s == "qrybrlyconmapflight") return QRYBRLYCONMAPFLIGHT;
	if (s == "qrybrlyconmapleg") return QRYBRLYCONMAPLEG;
	if (s == "qrybrlyconmaplocation") return QRYBRLYCONMAPLOCATION;
	if (s == "qrybrlyconmapnode") return QRYBRLYCONMAPNODE;
	if (s == "qrybrlyconmaprelay") return QRYBRLYCONMAPRELAY;
	if (s == "qrybrlyconmnflight") return QRYBRLYCONMNFLIGHT;
	if (s == "qrybrlyconmnsegment") return QRYBRLYCONMNSEGMENT;
	if (s == "qrybrlyconref1nsegment") return QRYBRLYCONREF1NSEGMENT;
	if (s == "qrybrlyfillist") return QRYBRLYFILLIST;
	if (s == "qrybrlyflt1nconnection") return QRYBRLYFLT1NCONNECTION;
	if (s == "qrybrlyflteqp1nnode") return QRYBRLYFLTEQP1NNODE;
	if (s == "qrybrlyflteqpmnconnection") return QRYBRLYFLTEQPMNCONNECTION;
	if (s == "qrybrlyfltfafawaypoint") return QRYBRLYFLTFAFAWAYPOINT;
	if (s == "qrybrlyfltlist") return QRYBRLYFLTLIST;
	if (s == "qrybrlyfltmnconnection") return QRYBRLYFLTMNCONNECTION;
	if (s == "qrybrlyfltmnlocation") return QRYBRLYFLTMNLOCATION;
	if (s == "qrybrlyfltorgmnflight") return QRYBRLYFLTORGMNFLIGHT;
	if (s == "qrybrlyfltref1nsegment") return QRYBRLYFLTREF1NSEGMENT;
	if (s == "qrybrlyleg1nflight") return QRYBRLYLEG1NFLIGHT;
	if (s == "qrybrlylegcor1nconnection") return QRYBRLYLEGCOR1NCONNECTION;
	if (s == "qrybrlyleglist") return QRYBRLYLEGLIST;
	if (s == "qrybrlylegmapleg") return QRYBRLYLEGMAPLEG;
	if (s == "qrybrlylegmaplocation") return QRYBRLYLEGMAPLOCATION;
	if (s == "qrybrlylegmnlocation") return QRYBRLYLEGMNLOCATION;
	if (s == "qrybrlylegorgmnleg") return QRYBRLYLEGORGMNLEG;
	if (s == "qrybrlylocbgn1nleg") return QRYBRLYLOCBGN1NLEG;
	if (s == "qrybrlylocend1nleg") return QRYBRLYLOCEND1NLEG;
	if (s == "qrybrlyloceqp1nnode") return QRYBRLYLOCEQP1NNODE;
	if (s == "qrybrlyloceqpmnconnection") return QRYBRLYLOCEQPMNCONNECTION;
	if (s == "qrybrlyloclist") return QRYBRLYLOCLIST;
	if (s == "qrybrlylocmapleg") return QRYBRLYLOCMAPLEG;
	if (s == "qrybrlylocmapproxlocation") return QRYBRLYLOCMAPPROXLOCATION;
	if (s == "qrybrlylocmapvislocation") return QRYBRLYLOCMAPVISLOCATION;
	if (s == "qrybrlylocmnflight") return QRYBRLYLOCMNFLIGHT;
	if (s == "qrybrlylocmnleg") return QRYBRLYLOCMNLEG;
	if (s == "qrybrlylocmnsegment") return QRYBRLYLOCMNSEGMENT;
	if (s == "qrybrlylocproxorgmnlocation") return QRYBRLYLOCPROXORGMNLOCATION;
	if (s == "qrybrlylocvisorgmnlocation") return QRYBRLYLOCVISORGMNLOCATION;
	if (s == "qrybrlyopr1nequipment") return QRYBRLYOPR1NEQUIPMENT;
	if (s == "qrybrlyoprlist") return QRYBRLYOPRLIST;
	if (s == "qrybrlyprsadetail") return QRYBRLYPRSADETAIL;
	if (s == "qrybrlyprslist") return QRYBRLYPRSLIST;
	if (s == "qrybrlypty1nequipment") return QRYBRLYPTY1NEQUIPMENT;
	if (s == "qrybrlyptylist") return QRYBRLYPTYLIST;
	if (s == "qrybrlyreg1nlocation") return QRYBRLYREG1NLOCATION;
	if (s == "qrybrlyregadstswitch") return QRYBRLYREGADSTSWITCH;
	if (s == "qrybrlyreglist") return QRYBRLYREGLIST;
	if (s == "qrybrlyregsup1nregion") return QRYBRLYREGSUP1NREGION;
	if (s == "qrybrlyrly1nnode") return QRYBRLYRLY1NNODE;
	if (s == "qrybrlyrlylist") return QRYBRLYRLYLIST;
	if (s == "qrybrlyseglist") return QRYBRLYSEGLIST;
	if (s == "qrybrlysegmnconnection") return QRYBRLYSEGMNCONNECTION;
	if (s == "qrybrlysegmnlocation") return QRYBRLYSEGMNLOCATION;
	if (s == "qrybrlysegorgmnsegment") return QRYBRLYSEGORGMNSEGMENT;
	if (s == "qrybrlyttb1nflight") return QRYBRLYTTB1NFLIGHT;
	if (s == "qrybrlyttblist") return QRYBRLYTTBLIST;
	if (s == "qrybrlyttbref1nfile") return QRYBRLYTTBREF1NFILE;
	if (s == "qrybrlyusgaaccess") return QRYBRLYUSGAACCESS;
	if (s == "qrybrlyusglist") return QRYBRLYUSGLIST;
	if (s == "qrybrlyusgmnuser") return QRYBRLYUSGMNUSER;
	if (s == "qrybrlyusr1nsession") return QRYBRLYUSR1NSESSION;
	if (s == "qrybrlyusraaccess") return QRYBRLYUSRAACCESS;
	if (s == "qrybrlyusrlist") return QRYBRLYUSRLIST;
	if (s == "qrybrlyusrmnusergroup") return QRYBRLYUSRMNUSERGROUP;
	if (s == "rootbrly") return ROOTBRLY;
	if (s == "sessbrly") return SESSBRLY;

	return(0);
};

string VecBrlyVJob::getSref(
			const uint ix
		) {
	if (ix == CRDBRLYCON) return("CrdBrlyCon");
	if (ix == CRDBRLYFIL) return("CrdBrlyFil");
	if (ix == CRDBRLYFLT) return("CrdBrlyFlt");
	if (ix == CRDBRLYLEG) return("CrdBrlyLeg");
	if (ix == CRDBRLYLOC) return("CrdBrlyLoc");
	if (ix == CRDBRLYNAV) return("CrdBrlyNav");
	if (ix == CRDBRLYOPR) return("CrdBrlyOpr");
	if (ix == CRDBRLYPRS) return("CrdBrlyPrs");
	if (ix == CRDBRLYPTY) return("CrdBrlyPty");
	if (ix == CRDBRLYREG) return("CrdBrlyReg");
	if (ix == CRDBRLYRLY) return("CrdBrlyRly");
	if (ix == CRDBRLYSEG) return("CrdBrlySeg");
	if (ix == CRDBRLYTTB) return("CrdBrlyTtb");
	if (ix == CRDBRLYUSG) return("CrdBrlyUsg");
	if (ix == CRDBRLYUSR) return("CrdBrlyUsr");
	if (ix == DLGBRLYCONNEW) return("DlgBrlyConNew");
	if (ix == DLGBRLYLEGNEW) return("DlgBrlyLegNew");
	if (ix == DLGBRLYNAVLOAINI) return("DlgBrlyNavLoaini");
	if (ix == DLGBRLYTTBIMPFLT) return("DlgBrlyTtbImpflt");
	if (ix == DLGBRLYTTBNEW) return("DlgBrlyTtbNew");
	if (ix == DLGBRLYTTBTRLORIG) return("DlgBrlyTtbTrlorig");
	if (ix == JOBBRLYIEXFLT) return("JobBrlyIexFlt");
	if (ix == JOBBRLYIEXINI) return("JobBrlyIexIni");
	if (ix == JOBBRLYIEXTTB) return("JobBrlyIexTtb");
	if (ix == PNLBRLYCON1NRELAY) return("PnlBrlyCon1NRelay");
	if (ix == PNLBRLYCONCONMNEQUIPMENT) return("PnlBrlyConConMNEquipment");
	if (ix == PNLBRLYCONDETAIL) return("PnlBrlyConDetail");
	if (ix == PNLBRLYCONHEADBAR) return("PnlBrlyConHeadbar");
	if (ix == PNLBRLYCONLIST) return("PnlBrlyConList");
	if (ix == PNLBRLYCONMAP) return("PnlBrlyConMap");
	if (ix == PNLBRLYCONMNFLIGHT) return("PnlBrlyConMNFlight");
	if (ix == PNLBRLYCONMNSEGMENT) return("PnlBrlyConMNSegment");
	if (ix == PNLBRLYCONPRE) return("PnlBrlyConPre");
	if (ix == PNLBRLYCONREC) return("PnlBrlyConRec");
	if (ix == PNLBRLYCONREF1NSEGMENT) return("PnlBrlyConRef1NSegment");
	if (ix == PNLBRLYFILDETAIL) return("PnlBrlyFilDetail");
	if (ix == PNLBRLYFILHEADBAR) return("PnlBrlyFilHeadbar");
	if (ix == PNLBRLYFILLIST) return("PnlBrlyFilList");
	if (ix == PNLBRLYFILREC) return("PnlBrlyFilRec");
	if (ix == PNLBRLYFLT1NCONNECTION) return("PnlBrlyFlt1NConnection");
	if (ix == PNLBRLYFLTDETAIL) return("PnlBrlyFltDetail");
	if (ix == PNLBRLYFLTEQP1NNODE) return("PnlBrlyFltEqp1NNode");
	if (ix == PNLBRLYFLTEQPMNCONNECTION) return("PnlBrlyFltEqpMNConnection");
	if (ix == PNLBRLYFLTFAFAWAYPOINT) return("PnlBrlyFltFafAWaypoint");
	if (ix == PNLBRLYFLTHEADBAR) return("PnlBrlyFltHeadbar");
	if (ix == PNLBRLYFLTLIST) return("PnlBrlyFltList");
	if (ix == PNLBRLYFLTMNCONNECTION) return("PnlBrlyFltMNConnection");
	if (ix == PNLBRLYFLTMNLOCATION) return("PnlBrlyFltMNLocation");
	if (ix == PNLBRLYFLTORGMNFLIGHT) return("PnlBrlyFltOrgMNFlight");
	if (ix == PNLBRLYFLTPRE) return("PnlBrlyFltPre");
	if (ix == PNLBRLYFLTREC) return("PnlBrlyFltRec");
	if (ix == PNLBRLYFLTREF1NSEGMENT) return("PnlBrlyFltRef1NSegment");
	if (ix == PNLBRLYLEG1NFLIGHT) return("PnlBrlyLeg1NFlight");
	if (ix == PNLBRLYLEGCOR1NCONNECTION) return("PnlBrlyLegCor1NConnection");
	if (ix == PNLBRLYLEGDETAIL) return("PnlBrlyLegDetail");
	if (ix == PNLBRLYLEGHEADBAR) return("PnlBrlyLegHeadbar");
	if (ix == PNLBRLYLEGLIST) return("PnlBrlyLegList");
	if (ix == PNLBRLYLEGMAP) return("PnlBrlyLegMap");
	if (ix == PNLBRLYLEGMNLOCATION) return("PnlBrlyLegMNLocation");
	if (ix == PNLBRLYLEGORGMNLEG) return("PnlBrlyLegOrgMNLeg");
	if (ix == PNLBRLYLEGPRE) return("PnlBrlyLegPre");
	if (ix == PNLBRLYLEGREC) return("PnlBrlyLegRec");
	if (ix == PNLBRLYLOCBGN1NLEG) return("PnlBrlyLocBgn1NLeg");
	if (ix == PNLBRLYLOCDETAIL) return("PnlBrlyLocDetail");
	if (ix == PNLBRLYLOCEND1NLEG) return("PnlBrlyLocEnd1NLeg");
	if (ix == PNLBRLYLOCEQP1NNODE) return("PnlBrlyLocEqp1NNode");
	if (ix == PNLBRLYLOCEQPMNCONNECTION) return("PnlBrlyLocEqpMNConnection");
	if (ix == PNLBRLYLOCHEADBAR) return("PnlBrlyLocHeadbar");
	if (ix == PNLBRLYLOCLIST) return("PnlBrlyLocList");
	if (ix == PNLBRLYLOCMAP) return("PnlBrlyLocMap");
	if (ix == PNLBRLYLOCMNFLIGHT) return("PnlBrlyLocMNFlight");
	if (ix == PNLBRLYLOCMNLEG) return("PnlBrlyLocMNLeg");
	if (ix == PNLBRLYLOCMNSEGMENT) return("PnlBrlyLocMNSegment");
	if (ix == PNLBRLYLOCPROXORGMNLOCATION) return("PnlBrlyLocProxOrgMNLocation");
	if (ix == PNLBRLYLOCREC) return("PnlBrlyLocRec");
	if (ix == PNLBRLYLOCVISORGMNLOCATION) return("PnlBrlyLocVisOrgMNLocation");
	if (ix == PNLBRLYNAVADMIN) return("PnlBrlyNavAdmin");
	if (ix == PNLBRLYNAVBASE) return("PnlBrlyNavBase");
	if (ix == PNLBRLYNAVCONNECT) return("PnlBrlyNavConnect");
	if (ix == PNLBRLYNAVHEADBAR) return("PnlBrlyNavHeadbar");
	if (ix == PNLBRLYOPR1NEQUIPMENT) return("PnlBrlyOpr1NEquipment");
	if (ix == PNLBRLYOPRDETAIL) return("PnlBrlyOprDetail");
	if (ix == PNLBRLYOPRHEADBAR) return("PnlBrlyOprHeadbar");
	if (ix == PNLBRLYOPRLIST) return("PnlBrlyOprList");
	if (ix == PNLBRLYOPRREC) return("PnlBrlyOprRec");
	if (ix == PNLBRLYPRSADETAIL) return("PnlBrlyPrsADetail");
	if (ix == PNLBRLYPRSDETAIL) return("PnlBrlyPrsDetail");
	if (ix == PNLBRLYPRSHEADBAR) return("PnlBrlyPrsHeadbar");
	if (ix == PNLBRLYPRSLIST) return("PnlBrlyPrsList");
	if (ix == PNLBRLYPRSREC) return("PnlBrlyPrsRec");
	if (ix == PNLBRLYPTY1NEQUIPMENT) return("PnlBrlyPty1NEquipment");
	if (ix == PNLBRLYPTYDETAIL) return("PnlBrlyPtyDetail");
	if (ix == PNLBRLYPTYHEADBAR) return("PnlBrlyPtyHeadbar");
	if (ix == PNLBRLYPTYLIST) return("PnlBrlyPtyList");
	if (ix == PNLBRLYPTYREC) return("PnlBrlyPtyRec");
	if (ix == PNLBRLYREG1NLOCATION) return("PnlBrlyReg1NLocation");
	if (ix == PNLBRLYREGADSTSWITCH) return("PnlBrlyRegADstswitch");
	if (ix == PNLBRLYREGDETAIL) return("PnlBrlyRegDetail");
	if (ix == PNLBRLYREGHEADBAR) return("PnlBrlyRegHeadbar");
	if (ix == PNLBRLYREGLIST) return("PnlBrlyRegList");
	if (ix == PNLBRLYREGREC) return("PnlBrlyRegRec");
	if (ix == PNLBRLYREGSUP1NREGION) return("PnlBrlyRegSup1NRegion");
	if (ix == PNLBRLYRLY1NNODE) return("PnlBrlyRly1NNode");
	if (ix == PNLBRLYRLYDETAIL) return("PnlBrlyRlyDetail");
	if (ix == PNLBRLYRLYHEADBAR) return("PnlBrlyRlyHeadbar");
	if (ix == PNLBRLYRLYLIST) return("PnlBrlyRlyList");
	if (ix == PNLBRLYRLYREC) return("PnlBrlyRlyRec");
	if (ix == PNLBRLYSEGDETAIL) return("PnlBrlySegDetail");
	if (ix == PNLBRLYSEGHEADBAR) return("PnlBrlySegHeadbar");
	if (ix == PNLBRLYSEGLIST) return("PnlBrlySegList");
	if (ix == PNLBRLYSEGMNCONNECTION) return("PnlBrlySegMNConnection");
	if (ix == PNLBRLYSEGMNLOCATION) return("PnlBrlySegMNLocation");
	if (ix == PNLBRLYSEGORGMNSEGMENT) return("PnlBrlySegOrgMNSegment");
	if (ix == PNLBRLYSEGPRE) return("PnlBrlySegPre");
	if (ix == PNLBRLYSEGREC) return("PnlBrlySegRec");
	if (ix == PNLBRLYTTB1NFLIGHT) return("PnlBrlyTtb1NFlight");
	if (ix == PNLBRLYTTBDETAIL) return("PnlBrlyTtbDetail");
	if (ix == PNLBRLYTTBHEADBAR) return("PnlBrlyTtbHeadbar");
	if (ix == PNLBRLYTTBLIST) return("PnlBrlyTtbList");
	if (ix == PNLBRLYTTBREC) return("PnlBrlyTtbRec");
	if (ix == PNLBRLYTTBREF1NFILE) return("PnlBrlyTtbRef1NFile");
	if (ix == PNLBRLYUSGAACCESS) return("PnlBrlyUsgAAccess");
	if (ix == PNLBRLYUSGDETAIL) return("PnlBrlyUsgDetail");
	if (ix == PNLBRLYUSGHEADBAR) return("PnlBrlyUsgHeadbar");
	if (ix == PNLBRLYUSGLIST) return("PnlBrlyUsgList");
	if (ix == PNLBRLYUSGMNUSER) return("PnlBrlyUsgMNUser");
	if (ix == PNLBRLYUSGREC) return("PnlBrlyUsgRec");
	if (ix == PNLBRLYUSR1NSESSION) return("PnlBrlyUsr1NSession");
	if (ix == PNLBRLYUSRAACCESS) return("PnlBrlyUsrAAccess");
	if (ix == PNLBRLYUSRDETAIL) return("PnlBrlyUsrDetail");
	if (ix == PNLBRLYUSRHEADBAR) return("PnlBrlyUsrHeadbar");
	if (ix == PNLBRLYUSRLIST) return("PnlBrlyUsrList");
	if (ix == PNLBRLYUSRMNUSERGROUP) return("PnlBrlyUsrMNUsergroup");
	if (ix == PNLBRLYUSRREC) return("PnlBrlyUsrRec");
	if (ix == QRYBRLYCON1NRELAY) return("QryBrlyCon1NRelay");
	if (ix == QRYBRLYCONCONMNEQUIPMENT) return("QryBrlyConConMNEquipment");
	if (ix == QRYBRLYCONLIST) return("QryBrlyConList");
	if (ix == QRYBRLYCONMAPFLIGHT) return("QryBrlyConMapFlight");
	if (ix == QRYBRLYCONMAPLEG) return("QryBrlyConMapLeg");
	if (ix == QRYBRLYCONMAPLOCATION) return("QryBrlyConMapLocation");
	if (ix == QRYBRLYCONMAPNODE) return("QryBrlyConMapNode");
	if (ix == QRYBRLYCONMAPRELAY) return("QryBrlyConMapRelay");
	if (ix == QRYBRLYCONMNFLIGHT) return("QryBrlyConMNFlight");
	if (ix == QRYBRLYCONMNSEGMENT) return("QryBrlyConMNSegment");
	if (ix == QRYBRLYCONREF1NSEGMENT) return("QryBrlyConRef1NSegment");
	if (ix == QRYBRLYFILLIST) return("QryBrlyFilList");
	if (ix == QRYBRLYFLT1NCONNECTION) return("QryBrlyFlt1NConnection");
	if (ix == QRYBRLYFLTEQP1NNODE) return("QryBrlyFltEqp1NNode");
	if (ix == QRYBRLYFLTEQPMNCONNECTION) return("QryBrlyFltEqpMNConnection");
	if (ix == QRYBRLYFLTFAFAWAYPOINT) return("QryBrlyFltFafAWaypoint");
	if (ix == QRYBRLYFLTLIST) return("QryBrlyFltList");
	if (ix == QRYBRLYFLTMNCONNECTION) return("QryBrlyFltMNConnection");
	if (ix == QRYBRLYFLTMNLOCATION) return("QryBrlyFltMNLocation");
	if (ix == QRYBRLYFLTORGMNFLIGHT) return("QryBrlyFltOrgMNFlight");
	if (ix == QRYBRLYFLTREF1NSEGMENT) return("QryBrlyFltRef1NSegment");
	if (ix == QRYBRLYLEG1NFLIGHT) return("QryBrlyLeg1NFlight");
	if (ix == QRYBRLYLEGCOR1NCONNECTION) return("QryBrlyLegCor1NConnection");
	if (ix == QRYBRLYLEGLIST) return("QryBrlyLegList");
	if (ix == QRYBRLYLEGMAPLEG) return("QryBrlyLegMapLeg");
	if (ix == QRYBRLYLEGMAPLOCATION) return("QryBrlyLegMapLocation");
	if (ix == QRYBRLYLEGMNLOCATION) return("QryBrlyLegMNLocation");
	if (ix == QRYBRLYLEGORGMNLEG) return("QryBrlyLegOrgMNLeg");
	if (ix == QRYBRLYLOCBGN1NLEG) return("QryBrlyLocBgn1NLeg");
	if (ix == QRYBRLYLOCEND1NLEG) return("QryBrlyLocEnd1NLeg");
	if (ix == QRYBRLYLOCEQP1NNODE) return("QryBrlyLocEqp1NNode");
	if (ix == QRYBRLYLOCEQPMNCONNECTION) return("QryBrlyLocEqpMNConnection");
	if (ix == QRYBRLYLOCLIST) return("QryBrlyLocList");
	if (ix == QRYBRLYLOCMAPLEG) return("QryBrlyLocMapLeg");
	if (ix == QRYBRLYLOCMAPPROXLOCATION) return("QryBrlyLocMapProxLocation");
	if (ix == QRYBRLYLOCMAPVISLOCATION) return("QryBrlyLocMapVisLocation");
	if (ix == QRYBRLYLOCMNFLIGHT) return("QryBrlyLocMNFlight");
	if (ix == QRYBRLYLOCMNLEG) return("QryBrlyLocMNLeg");
	if (ix == QRYBRLYLOCMNSEGMENT) return("QryBrlyLocMNSegment");
	if (ix == QRYBRLYLOCPROXORGMNLOCATION) return("QryBrlyLocProxOrgMNLocation");
	if (ix == QRYBRLYLOCVISORGMNLOCATION) return("QryBrlyLocVisOrgMNLocation");
	if (ix == QRYBRLYOPR1NEQUIPMENT) return("QryBrlyOpr1NEquipment");
	if (ix == QRYBRLYOPRLIST) return("QryBrlyOprList");
	if (ix == QRYBRLYPRSADETAIL) return("QryBrlyPrsADetail");
	if (ix == QRYBRLYPRSLIST) return("QryBrlyPrsList");
	if (ix == QRYBRLYPTY1NEQUIPMENT) return("QryBrlyPty1NEquipment");
	if (ix == QRYBRLYPTYLIST) return("QryBrlyPtyList");
	if (ix == QRYBRLYREG1NLOCATION) return("QryBrlyReg1NLocation");
	if (ix == QRYBRLYREGADSTSWITCH) return("QryBrlyRegADstswitch");
	if (ix == QRYBRLYREGLIST) return("QryBrlyRegList");
	if (ix == QRYBRLYREGSUP1NREGION) return("QryBrlyRegSup1NRegion");
	if (ix == QRYBRLYRLY1NNODE) return("QryBrlyRly1NNode");
	if (ix == QRYBRLYRLYLIST) return("QryBrlyRlyList");
	if (ix == QRYBRLYSEGLIST) return("QryBrlySegList");
	if (ix == QRYBRLYSEGMNCONNECTION) return("QryBrlySegMNConnection");
	if (ix == QRYBRLYSEGMNLOCATION) return("QryBrlySegMNLocation");
	if (ix == QRYBRLYSEGORGMNSEGMENT) return("QryBrlySegOrgMNSegment");
	if (ix == QRYBRLYTTB1NFLIGHT) return("QryBrlyTtb1NFlight");
	if (ix == QRYBRLYTTBLIST) return("QryBrlyTtbList");
	if (ix == QRYBRLYTTBREF1NFILE) return("QryBrlyTtbRef1NFile");
	if (ix == QRYBRLYUSGAACCESS) return("QryBrlyUsgAAccess");
	if (ix == QRYBRLYUSGLIST) return("QryBrlyUsgList");
	if (ix == QRYBRLYUSGMNUSER) return("QryBrlyUsgMNUser");
	if (ix == QRYBRLYUSR1NSESSION) return("QryBrlyUsr1NSession");
	if (ix == QRYBRLYUSRAACCESS) return("QryBrlyUsrAAccess");
	if (ix == QRYBRLYUSRLIST) return("QryBrlyUsrList");
	if (ix == QRYBRLYUSRMNUSERGROUP) return("QryBrlyUsrMNUsergroup");
	if (ix == ROOTBRLY) return("RootBrly");
	if (ix == SESSBRLY) return("SessBrly");

	return("");
};
