/**
	* \file VecBrlyVDpch.cpp
	* vector VecBrlyVDpch (implementation)
	* \copyright (C) 2016-2020 MPSI Technologies GmbH
	* \author Alexander Wirthmueller (auto-generation)
	* \date created: 11 Jan 2021
  */
// IP header --- ABOVE

#include "VecBrlyVDpch.h"

using namespace std;
using namespace Sbecore;
using namespace Xmlio;

/******************************************************************************
 namespace VecBrlyVDpch
 ******************************************************************************/

uint VecBrlyVDpch::getIx(
			const string& sref
		) {
	string s = StrMod::lc(sref);

	if (s == "dpchappbrlyalert") return DPCHAPPBRLYALERT;
	if (s == "dpchappbrlycon1nrelaydata") return DPCHAPPBRLYCON1NRELAYDATA;
	if (s == "dpchappbrlycon1nrelaydo") return DPCHAPPBRLYCON1NRELAYDO;
	if (s == "dpchappbrlyconconmnequipmentdata") return DPCHAPPBRLYCONCONMNEQUIPMENTDATA;
	if (s == "dpchappbrlyconconmnequipmentdo") return DPCHAPPBRLYCONCONMNEQUIPMENTDO;
	if (s == "dpchappbrlycondetaildata") return DPCHAPPBRLYCONDETAILDATA;
	if (s == "dpchappbrlycondetaildo") return DPCHAPPBRLYCONDETAILDO;
	if (s == "dpchappbrlycondo") return DPCHAPPBRLYCONDO;
	if (s == "dpchappbrlyconlistdata") return DPCHAPPBRLYCONLISTDATA;
	if (s == "dpchappbrlyconlistdo") return DPCHAPPBRLYCONLISTDO;
	if (s == "dpchappbrlyconmapdata") return DPCHAPPBRLYCONMAPDATA;
	if (s == "dpchappbrlyconmapdo") return DPCHAPPBRLYCONMAPDO;
	if (s == "dpchappbrlyconmnflightdata") return DPCHAPPBRLYCONMNFLIGHTDATA;
	if (s == "dpchappbrlyconmnflightdo") return DPCHAPPBRLYCONMNFLIGHTDO;
	if (s == "dpchappbrlyconmnsegmentdata") return DPCHAPPBRLYCONMNSEGMENTDATA;
	if (s == "dpchappbrlyconmnsegmentdo") return DPCHAPPBRLYCONMNSEGMENTDO;
	if (s == "dpchappbrlyconpredata") return DPCHAPPBRLYCONPREDATA;
	if (s == "dpchappbrlyconrecdo") return DPCHAPPBRLYCONRECDO;
	if (s == "dpchappbrlyconref1nsegmentdata") return DPCHAPPBRLYCONREF1NSEGMENTDATA;
	if (s == "dpchappbrlyconref1nsegmentdo") return DPCHAPPBRLYCONREF1NSEGMENTDO;
	if (s == "dpchappbrlyfildetaildata") return DPCHAPPBRLYFILDETAILDATA;
	if (s == "dpchappbrlyfildetaildo") return DPCHAPPBRLYFILDETAILDO;
	if (s == "dpchappbrlyfildo") return DPCHAPPBRLYFILDO;
	if (s == "dpchappbrlyfillistdata") return DPCHAPPBRLYFILLISTDATA;
	if (s == "dpchappbrlyfillistdo") return DPCHAPPBRLYFILLISTDO;
	if (s == "dpchappbrlyfilrecdo") return DPCHAPPBRLYFILRECDO;
	if (s == "dpchappbrlyflt1nconnectiondata") return DPCHAPPBRLYFLT1NCONNECTIONDATA;
	if (s == "dpchappbrlyflt1nconnectiondo") return DPCHAPPBRLYFLT1NCONNECTIONDO;
	if (s == "dpchappbrlyfltdetaildata") return DPCHAPPBRLYFLTDETAILDATA;
	if (s == "dpchappbrlyfltdetaildo") return DPCHAPPBRLYFLTDETAILDO;
	if (s == "dpchappbrlyfltdo") return DPCHAPPBRLYFLTDO;
	if (s == "dpchappbrlyflteqp1nnodedata") return DPCHAPPBRLYFLTEQP1NNODEDATA;
	if (s == "dpchappbrlyflteqp1nnodedo") return DPCHAPPBRLYFLTEQP1NNODEDO;
	if (s == "dpchappbrlyflteqpmnconnectiondata") return DPCHAPPBRLYFLTEQPMNCONNECTIONDATA;
	if (s == "dpchappbrlyflteqpmnconnectiondo") return DPCHAPPBRLYFLTEQPMNCONNECTIONDO;
	if (s == "dpchappbrlyfltfafawaypointdata") return DPCHAPPBRLYFLTFAFAWAYPOINTDATA;
	if (s == "dpchappbrlyfltfafawaypointdo") return DPCHAPPBRLYFLTFAFAWAYPOINTDO;
	if (s == "dpchappbrlyfltlistdata") return DPCHAPPBRLYFLTLISTDATA;
	if (s == "dpchappbrlyfltlistdo") return DPCHAPPBRLYFLTLISTDO;
	if (s == "dpchappbrlyfltmnconnectiondata") return DPCHAPPBRLYFLTMNCONNECTIONDATA;
	if (s == "dpchappbrlyfltmnconnectiondo") return DPCHAPPBRLYFLTMNCONNECTIONDO;
	if (s == "dpchappbrlyfltmnlocationdata") return DPCHAPPBRLYFLTMNLOCATIONDATA;
	if (s == "dpchappbrlyfltmnlocationdo") return DPCHAPPBRLYFLTMNLOCATIONDO;
	if (s == "dpchappbrlyfltorgmnflightdata") return DPCHAPPBRLYFLTORGMNFLIGHTDATA;
	if (s == "dpchappbrlyfltorgmnflightdo") return DPCHAPPBRLYFLTORGMNFLIGHTDO;
	if (s == "dpchappbrlyfltpredata") return DPCHAPPBRLYFLTPREDATA;
	if (s == "dpchappbrlyfltrecdo") return DPCHAPPBRLYFLTRECDO;
	if (s == "dpchappbrlyfltref1nsegmentdata") return DPCHAPPBRLYFLTREF1NSEGMENTDATA;
	if (s == "dpchappbrlyfltref1nsegmentdo") return DPCHAPPBRLYFLTREF1NSEGMENTDO;
	if (s == "dpchappbrlyinit") return DPCHAPPBRLYINIT;
	if (s == "dpchappbrlyleg1nflightdata") return DPCHAPPBRLYLEG1NFLIGHTDATA;
	if (s == "dpchappbrlyleg1nflightdo") return DPCHAPPBRLYLEG1NFLIGHTDO;
	if (s == "dpchappbrlylegcor1nconnectiondata") return DPCHAPPBRLYLEGCOR1NCONNECTIONDATA;
	if (s == "dpchappbrlylegcor1nconnectiondo") return DPCHAPPBRLYLEGCOR1NCONNECTIONDO;
	if (s == "dpchappbrlylegdetaildata") return DPCHAPPBRLYLEGDETAILDATA;
	if (s == "dpchappbrlylegdetaildo") return DPCHAPPBRLYLEGDETAILDO;
	if (s == "dpchappbrlylegdo") return DPCHAPPBRLYLEGDO;
	if (s == "dpchappbrlyleglistdata") return DPCHAPPBRLYLEGLISTDATA;
	if (s == "dpchappbrlyleglistdo") return DPCHAPPBRLYLEGLISTDO;
	if (s == "dpchappbrlylegmapdata") return DPCHAPPBRLYLEGMAPDATA;
	if (s == "dpchappbrlylegmapdo") return DPCHAPPBRLYLEGMAPDO;
	if (s == "dpchappbrlylegmnlocationdata") return DPCHAPPBRLYLEGMNLOCATIONDATA;
	if (s == "dpchappbrlylegmnlocationdo") return DPCHAPPBRLYLEGMNLOCATIONDO;
	if (s == "dpchappbrlylegorgmnlegdata") return DPCHAPPBRLYLEGORGMNLEGDATA;
	if (s == "dpchappbrlylegorgmnlegdo") return DPCHAPPBRLYLEGORGMNLEGDO;
	if (s == "dpchappbrlylegpredata") return DPCHAPPBRLYLEGPREDATA;
	if (s == "dpchappbrlylegrecdo") return DPCHAPPBRLYLEGRECDO;
	if (s == "dpchappbrlylocbgn1nlegdata") return DPCHAPPBRLYLOCBGN1NLEGDATA;
	if (s == "dpchappbrlylocbgn1nlegdo") return DPCHAPPBRLYLOCBGN1NLEGDO;
	if (s == "dpchappbrlylocdetaildata") return DPCHAPPBRLYLOCDETAILDATA;
	if (s == "dpchappbrlylocdetaildo") return DPCHAPPBRLYLOCDETAILDO;
	if (s == "dpchappbrlylocdo") return DPCHAPPBRLYLOCDO;
	if (s == "dpchappbrlylocend1nlegdata") return DPCHAPPBRLYLOCEND1NLEGDATA;
	if (s == "dpchappbrlylocend1nlegdo") return DPCHAPPBRLYLOCEND1NLEGDO;
	if (s == "dpchappbrlyloceqp1nnodedata") return DPCHAPPBRLYLOCEQP1NNODEDATA;
	if (s == "dpchappbrlyloceqp1nnodedo") return DPCHAPPBRLYLOCEQP1NNODEDO;
	if (s == "dpchappbrlyloceqpmnconnectiondata") return DPCHAPPBRLYLOCEQPMNCONNECTIONDATA;
	if (s == "dpchappbrlyloceqpmnconnectiondo") return DPCHAPPBRLYLOCEQPMNCONNECTIONDO;
	if (s == "dpchappbrlyloclistdata") return DPCHAPPBRLYLOCLISTDATA;
	if (s == "dpchappbrlyloclistdo") return DPCHAPPBRLYLOCLISTDO;
	if (s == "dpchappbrlylocmapdata") return DPCHAPPBRLYLOCMAPDATA;
	if (s == "dpchappbrlylocmapdo") return DPCHAPPBRLYLOCMAPDO;
	if (s == "dpchappbrlylocmnflightdata") return DPCHAPPBRLYLOCMNFLIGHTDATA;
	if (s == "dpchappbrlylocmnflightdo") return DPCHAPPBRLYLOCMNFLIGHTDO;
	if (s == "dpchappbrlylocmnlegdata") return DPCHAPPBRLYLOCMNLEGDATA;
	if (s == "dpchappbrlylocmnlegdo") return DPCHAPPBRLYLOCMNLEGDO;
	if (s == "dpchappbrlylocmnsegmentdata") return DPCHAPPBRLYLOCMNSEGMENTDATA;
	if (s == "dpchappbrlylocmnsegmentdo") return DPCHAPPBRLYLOCMNSEGMENTDO;
	if (s == "dpchappbrlylocproxorgmnlocationdata") return DPCHAPPBRLYLOCPROXORGMNLOCATIONDATA;
	if (s == "dpchappbrlylocproxorgmnlocationdo") return DPCHAPPBRLYLOCPROXORGMNLOCATIONDO;
	if (s == "dpchappbrlylocrecdo") return DPCHAPPBRLYLOCRECDO;
	if (s == "dpchappbrlylocvisorgmnlocationdata") return DPCHAPPBRLYLOCVISORGMNLOCATIONDATA;
	if (s == "dpchappbrlylocvisorgmnlocationdo") return DPCHAPPBRLYLOCVISORGMNLOCATIONDO;
	if (s == "dpchappbrlynavadmindata") return DPCHAPPBRLYNAVADMINDATA;
	if (s == "dpchappbrlynavadmindo") return DPCHAPPBRLYNAVADMINDO;
	if (s == "dpchappbrlynavbasedata") return DPCHAPPBRLYNAVBASEDATA;
	if (s == "dpchappbrlynavbasedo") return DPCHAPPBRLYNAVBASEDO;
	if (s == "dpchappbrlynavconnectdata") return DPCHAPPBRLYNAVCONNECTDATA;
	if (s == "dpchappbrlynavconnectdo") return DPCHAPPBRLYNAVCONNECTDO;
	if (s == "dpchappbrlynavdo") return DPCHAPPBRLYNAVDO;
	if (s == "dpchappbrlyopr1nequipmentdata") return DPCHAPPBRLYOPR1NEQUIPMENTDATA;
	if (s == "dpchappbrlyopr1nequipmentdo") return DPCHAPPBRLYOPR1NEQUIPMENTDO;
	if (s == "dpchappbrlyoprdetaildata") return DPCHAPPBRLYOPRDETAILDATA;
	if (s == "dpchappbrlyoprdetaildo") return DPCHAPPBRLYOPRDETAILDO;
	if (s == "dpchappbrlyoprdo") return DPCHAPPBRLYOPRDO;
	if (s == "dpchappbrlyoprlistdata") return DPCHAPPBRLYOPRLISTDATA;
	if (s == "dpchappbrlyoprlistdo") return DPCHAPPBRLYOPRLISTDO;
	if (s == "dpchappbrlyoprrecdo") return DPCHAPPBRLYOPRRECDO;
	if (s == "dpchappbrlyprsadetaildata") return DPCHAPPBRLYPRSADETAILDATA;
	if (s == "dpchappbrlyprsadetaildo") return DPCHAPPBRLYPRSADETAILDO;
	if (s == "dpchappbrlyprsdetaildata") return DPCHAPPBRLYPRSDETAILDATA;
	if (s == "dpchappbrlyprsdetaildo") return DPCHAPPBRLYPRSDETAILDO;
	if (s == "dpchappbrlyprsdo") return DPCHAPPBRLYPRSDO;
	if (s == "dpchappbrlyprslistdata") return DPCHAPPBRLYPRSLISTDATA;
	if (s == "dpchappbrlyprslistdo") return DPCHAPPBRLYPRSLISTDO;
	if (s == "dpchappbrlyprsrecdo") return DPCHAPPBRLYPRSRECDO;
	if (s == "dpchappbrlypty1nequipmentdata") return DPCHAPPBRLYPTY1NEQUIPMENTDATA;
	if (s == "dpchappbrlypty1nequipmentdo") return DPCHAPPBRLYPTY1NEQUIPMENTDO;
	if (s == "dpchappbrlyptydetaildata") return DPCHAPPBRLYPTYDETAILDATA;
	if (s == "dpchappbrlyptydetaildo") return DPCHAPPBRLYPTYDETAILDO;
	if (s == "dpchappbrlyptydo") return DPCHAPPBRLYPTYDO;
	if (s == "dpchappbrlyptylistdata") return DPCHAPPBRLYPTYLISTDATA;
	if (s == "dpchappbrlyptylistdo") return DPCHAPPBRLYPTYLISTDO;
	if (s == "dpchappbrlyptyrecdo") return DPCHAPPBRLYPTYRECDO;
	if (s == "dpchappbrlyreg1nlocationdata") return DPCHAPPBRLYREG1NLOCATIONDATA;
	if (s == "dpchappbrlyreg1nlocationdo") return DPCHAPPBRLYREG1NLOCATIONDO;
	if (s == "dpchappbrlyregadstswitchdata") return DPCHAPPBRLYREGADSTSWITCHDATA;
	if (s == "dpchappbrlyregadstswitchdo") return DPCHAPPBRLYREGADSTSWITCHDO;
	if (s == "dpchappbrlyregdetaildata") return DPCHAPPBRLYREGDETAILDATA;
	if (s == "dpchappbrlyregdetaildo") return DPCHAPPBRLYREGDETAILDO;
	if (s == "dpchappbrlyregdo") return DPCHAPPBRLYREGDO;
	if (s == "dpchappbrlyreglistdata") return DPCHAPPBRLYREGLISTDATA;
	if (s == "dpchappbrlyreglistdo") return DPCHAPPBRLYREGLISTDO;
	if (s == "dpchappbrlyregrecdo") return DPCHAPPBRLYREGRECDO;
	if (s == "dpchappbrlyregsup1nregiondata") return DPCHAPPBRLYREGSUP1NREGIONDATA;
	if (s == "dpchappbrlyregsup1nregiondo") return DPCHAPPBRLYREGSUP1NREGIONDO;
	if (s == "dpchappbrlyresume") return DPCHAPPBRLYRESUME;
	if (s == "dpchappbrlyrly1nnodedata") return DPCHAPPBRLYRLY1NNODEDATA;
	if (s == "dpchappbrlyrly1nnodedo") return DPCHAPPBRLYRLY1NNODEDO;
	if (s == "dpchappbrlyrlydetaildata") return DPCHAPPBRLYRLYDETAILDATA;
	if (s == "dpchappbrlyrlydetaildo") return DPCHAPPBRLYRLYDETAILDO;
	if (s == "dpchappbrlyrlydo") return DPCHAPPBRLYRLYDO;
	if (s == "dpchappbrlyrlylistdata") return DPCHAPPBRLYRLYLISTDATA;
	if (s == "dpchappbrlyrlylistdo") return DPCHAPPBRLYRLYLISTDO;
	if (s == "dpchappbrlyrlyrecdo") return DPCHAPPBRLYRLYRECDO;
	if (s == "dpchappbrlysegdetaildata") return DPCHAPPBRLYSEGDETAILDATA;
	if (s == "dpchappbrlysegdetaildo") return DPCHAPPBRLYSEGDETAILDO;
	if (s == "dpchappbrlysegdo") return DPCHAPPBRLYSEGDO;
	if (s == "dpchappbrlyseglistdata") return DPCHAPPBRLYSEGLISTDATA;
	if (s == "dpchappbrlyseglistdo") return DPCHAPPBRLYSEGLISTDO;
	if (s == "dpchappbrlysegmnconnectiondata") return DPCHAPPBRLYSEGMNCONNECTIONDATA;
	if (s == "dpchappbrlysegmnconnectiondo") return DPCHAPPBRLYSEGMNCONNECTIONDO;
	if (s == "dpchappbrlysegmnlocationdata") return DPCHAPPBRLYSEGMNLOCATIONDATA;
	if (s == "dpchappbrlysegmnlocationdo") return DPCHAPPBRLYSEGMNLOCATIONDO;
	if (s == "dpchappbrlysegorgmnsegmentdata") return DPCHAPPBRLYSEGORGMNSEGMENTDATA;
	if (s == "dpchappbrlysegorgmnsegmentdo") return DPCHAPPBRLYSEGORGMNSEGMENTDO;
	if (s == "dpchappbrlysegpredata") return DPCHAPPBRLYSEGPREDATA;
	if (s == "dpchappbrlysegrecdo") return DPCHAPPBRLYSEGRECDO;
	if (s == "dpchappbrlyttb1nflightdata") return DPCHAPPBRLYTTB1NFLIGHTDATA;
	if (s == "dpchappbrlyttb1nflightdo") return DPCHAPPBRLYTTB1NFLIGHTDO;
	if (s == "dpchappbrlyttbdetaildata") return DPCHAPPBRLYTTBDETAILDATA;
	if (s == "dpchappbrlyttbdetaildo") return DPCHAPPBRLYTTBDETAILDO;
	if (s == "dpchappbrlyttbdo") return DPCHAPPBRLYTTBDO;
	if (s == "dpchappbrlyttblistdata") return DPCHAPPBRLYTTBLISTDATA;
	if (s == "dpchappbrlyttblistdo") return DPCHAPPBRLYTTBLISTDO;
	if (s == "dpchappbrlyttbrecdo") return DPCHAPPBRLYTTBRECDO;
	if (s == "dpchappbrlyttbref1nfiledata") return DPCHAPPBRLYTTBREF1NFILEDATA;
	if (s == "dpchappbrlyttbref1nfiledo") return DPCHAPPBRLYTTBREF1NFILEDO;
	if (s == "dpchappbrlyusgaaccessdata") return DPCHAPPBRLYUSGAACCESSDATA;
	if (s == "dpchappbrlyusgaaccessdo") return DPCHAPPBRLYUSGAACCESSDO;
	if (s == "dpchappbrlyusgdetaildata") return DPCHAPPBRLYUSGDETAILDATA;
	if (s == "dpchappbrlyusgdetaildo") return DPCHAPPBRLYUSGDETAILDO;
	if (s == "dpchappbrlyusgdo") return DPCHAPPBRLYUSGDO;
	if (s == "dpchappbrlyusglistdata") return DPCHAPPBRLYUSGLISTDATA;
	if (s == "dpchappbrlyusglistdo") return DPCHAPPBRLYUSGLISTDO;
	if (s == "dpchappbrlyusgmnuserdata") return DPCHAPPBRLYUSGMNUSERDATA;
	if (s == "dpchappbrlyusgmnuserdo") return DPCHAPPBRLYUSGMNUSERDO;
	if (s == "dpchappbrlyusgrecdo") return DPCHAPPBRLYUSGRECDO;
	if (s == "dpchappbrlyusr1nsessiondata") return DPCHAPPBRLYUSR1NSESSIONDATA;
	if (s == "dpchappbrlyusr1nsessiondo") return DPCHAPPBRLYUSR1NSESSIONDO;
	if (s == "dpchappbrlyusraaccessdata") return DPCHAPPBRLYUSRAACCESSDATA;
	if (s == "dpchappbrlyusraaccessdo") return DPCHAPPBRLYUSRAACCESSDO;
	if (s == "dpchappbrlyusrdetaildata") return DPCHAPPBRLYUSRDETAILDATA;
	if (s == "dpchappbrlyusrdetaildo") return DPCHAPPBRLYUSRDETAILDO;
	if (s == "dpchappbrlyusrdo") return DPCHAPPBRLYUSRDO;
	if (s == "dpchappbrlyusrlistdata") return DPCHAPPBRLYUSRLISTDATA;
	if (s == "dpchappbrlyusrlistdo") return DPCHAPPBRLYUSRLISTDO;
	if (s == "dpchappbrlyusrmnusergroupdata") return DPCHAPPBRLYUSRMNUSERGROUPDATA;
	if (s == "dpchappbrlyusrmnusergroupdo") return DPCHAPPBRLYUSRMNUSERGROUPDO;
	if (s == "dpchappbrlyusrrecdo") return DPCHAPPBRLYUSRRECDO;
	if (s == "dpchappdlgbrlyconnewdata") return DPCHAPPDLGBRLYCONNEWDATA;
	if (s == "dpchappdlgbrlyconnewdo") return DPCHAPPDLGBRLYCONNEWDO;
	if (s == "dpchappdlgbrlylegnewdata") return DPCHAPPDLGBRLYLEGNEWDATA;
	if (s == "dpchappdlgbrlylegnewdo") return DPCHAPPDLGBRLYLEGNEWDO;
	if (s == "dpchappdlgbrlynavloainidata") return DPCHAPPDLGBRLYNAVLOAINIDATA;
	if (s == "dpchappdlgbrlynavloainido") return DPCHAPPDLGBRLYNAVLOAINIDO;
	if (s == "dpchappdlgbrlyttbimpfltdata") return DPCHAPPDLGBRLYTTBIMPFLTDATA;
	if (s == "dpchappdlgbrlyttbimpfltdo") return DPCHAPPDLGBRLYTTBIMPFLTDO;
	if (s == "dpchappdlgbrlyttbnewdata") return DPCHAPPDLGBRLYTTBNEWDATA;
	if (s == "dpchappdlgbrlyttbnewdo") return DPCHAPPDLGBRLYTTBNEWDO;
	if (s == "dpchappdlgbrlyttbtrlorigdata") return DPCHAPPDLGBRLYTTBTRLORIGDATA;
	if (s == "dpchappdlgbrlyttbtrlorigdo") return DPCHAPPDLGBRLYTTBTRLORIGDO;
	if (s == "dpchapprootbrlylogin") return DPCHAPPROOTBRLYLOGIN;
	if (s == "dpchbrlydack") return DPCHBRLYDACK;
	if (s == "dpchbrlydquit") return DPCHBRLYDQUIT;
	if (s == "dpchbrlydreg") return DPCHBRLYDREG;
	if (s == "dpchbrlyopdreg") return DPCHBRLYOPDREG;
	if (s == "dpchbrlyopdunreg") return DPCHBRLYOPDUNREG;
	if (s == "dpchengbrlyack") return DPCHENGBRLYACK;
	if (s == "dpchengbrlyalert") return DPCHENGBRLYALERT;
	if (s == "dpchengbrlycon1nrelaydata") return DPCHENGBRLYCON1NRELAYDATA;
	if (s == "dpchengbrlyconconmnequipmentdata") return DPCHENGBRLYCONCONMNEQUIPMENTDATA;
	if (s == "dpchengbrlycondata") return DPCHENGBRLYCONDATA;
	if (s == "dpchengbrlycondetaildata") return DPCHENGBRLYCONDETAILDATA;
	if (s == "dpchengbrlyconfirm") return DPCHENGBRLYCONFIRM;
	if (s == "dpchengbrlyconheadbardata") return DPCHENGBRLYCONHEADBARDATA;
	if (s == "dpchengbrlyconlistdata") return DPCHENGBRLYCONLISTDATA;
	if (s == "dpchengbrlyconmapdata") return DPCHENGBRLYCONMAPDATA;
	if (s == "dpchengbrlyconmapimage") return DPCHENGBRLYCONMAPIMAGE;
	if (s == "dpchengbrlyconmnflightdata") return DPCHENGBRLYCONMNFLIGHTDATA;
	if (s == "dpchengbrlyconmnsegmentdata") return DPCHENGBRLYCONMNSEGMENTDATA;
	if (s == "dpchengbrlyconpredata") return DPCHENGBRLYCONPREDATA;
	if (s == "dpchengbrlyconrecdata") return DPCHENGBRLYCONRECDATA;
	if (s == "dpchengbrlyconref1nsegmentdata") return DPCHENGBRLYCONREF1NSEGMENTDATA;
	if (s == "dpchengbrlyfildata") return DPCHENGBRLYFILDATA;
	if (s == "dpchengbrlyfildetaildata") return DPCHENGBRLYFILDETAILDATA;
	if (s == "dpchengbrlyfilheadbardata") return DPCHENGBRLYFILHEADBARDATA;
	if (s == "dpchengbrlyfillistdata") return DPCHENGBRLYFILLISTDATA;
	if (s == "dpchengbrlyfilrecdata") return DPCHENGBRLYFILRECDATA;
	if (s == "dpchengbrlyflt1nconnectiondata") return DPCHENGBRLYFLT1NCONNECTIONDATA;
	if (s == "dpchengbrlyfltdata") return DPCHENGBRLYFLTDATA;
	if (s == "dpchengbrlyfltdetaildata") return DPCHENGBRLYFLTDETAILDATA;
	if (s == "dpchengbrlyflteqp1nnodedata") return DPCHENGBRLYFLTEQP1NNODEDATA;
	if (s == "dpchengbrlyflteqpmnconnectiondata") return DPCHENGBRLYFLTEQPMNCONNECTIONDATA;
	if (s == "dpchengbrlyfltfafawaypointdata") return DPCHENGBRLYFLTFAFAWAYPOINTDATA;
	if (s == "dpchengbrlyfltheadbardata") return DPCHENGBRLYFLTHEADBARDATA;
	if (s == "dpchengbrlyfltlistdata") return DPCHENGBRLYFLTLISTDATA;
	if (s == "dpchengbrlyfltmnconnectiondata") return DPCHENGBRLYFLTMNCONNECTIONDATA;
	if (s == "dpchengbrlyfltmnlocationdata") return DPCHENGBRLYFLTMNLOCATIONDATA;
	if (s == "dpchengbrlyfltorgmnflightdata") return DPCHENGBRLYFLTORGMNFLIGHTDATA;
	if (s == "dpchengbrlyfltpredata") return DPCHENGBRLYFLTPREDATA;
	if (s == "dpchengbrlyfltrecdata") return DPCHENGBRLYFLTRECDATA;
	if (s == "dpchengbrlyfltref1nsegmentdata") return DPCHENGBRLYFLTREF1NSEGMENTDATA;
	if (s == "dpchengbrlyleg1nflightdata") return DPCHENGBRLYLEG1NFLIGHTDATA;
	if (s == "dpchengbrlylegcor1nconnectiondata") return DPCHENGBRLYLEGCOR1NCONNECTIONDATA;
	if (s == "dpchengbrlylegdata") return DPCHENGBRLYLEGDATA;
	if (s == "dpchengbrlylegdetaildata") return DPCHENGBRLYLEGDETAILDATA;
	if (s == "dpchengbrlylegheadbardata") return DPCHENGBRLYLEGHEADBARDATA;
	if (s == "dpchengbrlyleglistdata") return DPCHENGBRLYLEGLISTDATA;
	if (s == "dpchengbrlylegmapdata") return DPCHENGBRLYLEGMAPDATA;
	if (s == "dpchengbrlylegmapimage") return DPCHENGBRLYLEGMAPIMAGE;
	if (s == "dpchengbrlylegmnlocationdata") return DPCHENGBRLYLEGMNLOCATIONDATA;
	if (s == "dpchengbrlylegorgmnlegdata") return DPCHENGBRLYLEGORGMNLEGDATA;
	if (s == "dpchengbrlylegpredata") return DPCHENGBRLYLEGPREDATA;
	if (s == "dpchengbrlylegrecdata") return DPCHENGBRLYLEGRECDATA;
	if (s == "dpchengbrlylocbgn1nlegdata") return DPCHENGBRLYLOCBGN1NLEGDATA;
	if (s == "dpchengbrlylocdata") return DPCHENGBRLYLOCDATA;
	if (s == "dpchengbrlylocdetaildata") return DPCHENGBRLYLOCDETAILDATA;
	if (s == "dpchengbrlylocend1nlegdata") return DPCHENGBRLYLOCEND1NLEGDATA;
	if (s == "dpchengbrlyloceqp1nnodedata") return DPCHENGBRLYLOCEQP1NNODEDATA;
	if (s == "dpchengbrlyloceqpmnconnectiondata") return DPCHENGBRLYLOCEQPMNCONNECTIONDATA;
	if (s == "dpchengbrlylocheadbardata") return DPCHENGBRLYLOCHEADBARDATA;
	if (s == "dpchengbrlyloclistdata") return DPCHENGBRLYLOCLISTDATA;
	if (s == "dpchengbrlylocmapdata") return DPCHENGBRLYLOCMAPDATA;
	if (s == "dpchengbrlylocmapimage") return DPCHENGBRLYLOCMAPIMAGE;
	if (s == "dpchengbrlylocmnflightdata") return DPCHENGBRLYLOCMNFLIGHTDATA;
	if (s == "dpchengbrlylocmnlegdata") return DPCHENGBRLYLOCMNLEGDATA;
	if (s == "dpchengbrlylocmnsegmentdata") return DPCHENGBRLYLOCMNSEGMENTDATA;
	if (s == "dpchengbrlylocproxorgmnlocationdata") return DPCHENGBRLYLOCPROXORGMNLOCATIONDATA;
	if (s == "dpchengbrlylocrecdata") return DPCHENGBRLYLOCRECDATA;
	if (s == "dpchengbrlylocvisorgmnlocationdata") return DPCHENGBRLYLOCVISORGMNLOCATIONDATA;
	if (s == "dpchengbrlynavadmindata") return DPCHENGBRLYNAVADMINDATA;
	if (s == "dpchengbrlynavbasedata") return DPCHENGBRLYNAVBASEDATA;
	if (s == "dpchengbrlynavconnectdata") return DPCHENGBRLYNAVCONNECTDATA;
	if (s == "dpchengbrlynavdata") return DPCHENGBRLYNAVDATA;
	if (s == "dpchengbrlynavheadbardata") return DPCHENGBRLYNAVHEADBARDATA;
	if (s == "dpchengbrlyopr1nequipmentdata") return DPCHENGBRLYOPR1NEQUIPMENTDATA;
	if (s == "dpchengbrlyoprdata") return DPCHENGBRLYOPRDATA;
	if (s == "dpchengbrlyoprdetaildata") return DPCHENGBRLYOPRDETAILDATA;
	if (s == "dpchengbrlyoprheadbardata") return DPCHENGBRLYOPRHEADBARDATA;
	if (s == "dpchengbrlyoprlistdata") return DPCHENGBRLYOPRLISTDATA;
	if (s == "dpchengbrlyoprrecdata") return DPCHENGBRLYOPRRECDATA;
	if (s == "dpchengbrlyprsadetaildata") return DPCHENGBRLYPRSADETAILDATA;
	if (s == "dpchengbrlyprsdata") return DPCHENGBRLYPRSDATA;
	if (s == "dpchengbrlyprsdetaildata") return DPCHENGBRLYPRSDETAILDATA;
	if (s == "dpchengbrlyprsheadbardata") return DPCHENGBRLYPRSHEADBARDATA;
	if (s == "dpchengbrlyprslistdata") return DPCHENGBRLYPRSLISTDATA;
	if (s == "dpchengbrlyprsrecdata") return DPCHENGBRLYPRSRECDATA;
	if (s == "dpchengbrlypty1nequipmentdata") return DPCHENGBRLYPTY1NEQUIPMENTDATA;
	if (s == "dpchengbrlyptydata") return DPCHENGBRLYPTYDATA;
	if (s == "dpchengbrlyptydetaildata") return DPCHENGBRLYPTYDETAILDATA;
	if (s == "dpchengbrlyptyheadbardata") return DPCHENGBRLYPTYHEADBARDATA;
	if (s == "dpchengbrlyptylistdata") return DPCHENGBRLYPTYLISTDATA;
	if (s == "dpchengbrlyptyrecdata") return DPCHENGBRLYPTYRECDATA;
	if (s == "dpchengbrlyreg1nlocationdata") return DPCHENGBRLYREG1NLOCATIONDATA;
	if (s == "dpchengbrlyregadstswitchdata") return DPCHENGBRLYREGADSTSWITCHDATA;
	if (s == "dpchengbrlyregdata") return DPCHENGBRLYREGDATA;
	if (s == "dpchengbrlyregdetaildata") return DPCHENGBRLYREGDETAILDATA;
	if (s == "dpchengbrlyregheadbardata") return DPCHENGBRLYREGHEADBARDATA;
	if (s == "dpchengbrlyreglistdata") return DPCHENGBRLYREGLISTDATA;
	if (s == "dpchengbrlyregrecdata") return DPCHENGBRLYREGRECDATA;
	if (s == "dpchengbrlyregsup1nregiondata") return DPCHENGBRLYREGSUP1NREGIONDATA;
	if (s == "dpchengbrlyrly1nnodedata") return DPCHENGBRLYRLY1NNODEDATA;
	if (s == "dpchengbrlyrlydata") return DPCHENGBRLYRLYDATA;
	if (s == "dpchengbrlyrlydetaildata") return DPCHENGBRLYRLYDETAILDATA;
	if (s == "dpchengbrlyrlyheadbardata") return DPCHENGBRLYRLYHEADBARDATA;
	if (s == "dpchengbrlyrlylistdata") return DPCHENGBRLYRLYLISTDATA;
	if (s == "dpchengbrlyrlyrecdata") return DPCHENGBRLYRLYRECDATA;
	if (s == "dpchengbrlysegdata") return DPCHENGBRLYSEGDATA;
	if (s == "dpchengbrlysegdetaildata") return DPCHENGBRLYSEGDETAILDATA;
	if (s == "dpchengbrlysegheadbardata") return DPCHENGBRLYSEGHEADBARDATA;
	if (s == "dpchengbrlyseglistdata") return DPCHENGBRLYSEGLISTDATA;
	if (s == "dpchengbrlysegmnconnectiondata") return DPCHENGBRLYSEGMNCONNECTIONDATA;
	if (s == "dpchengbrlysegmnlocationdata") return DPCHENGBRLYSEGMNLOCATIONDATA;
	if (s == "dpchengbrlysegorgmnsegmentdata") return DPCHENGBRLYSEGORGMNSEGMENTDATA;
	if (s == "dpchengbrlysegpredata") return DPCHENGBRLYSEGPREDATA;
	if (s == "dpchengbrlysegrecdata") return DPCHENGBRLYSEGRECDATA;
	if (s == "dpchengbrlysuspend") return DPCHENGBRLYSUSPEND;
	if (s == "dpchengbrlyttb1nflightdata") return DPCHENGBRLYTTB1NFLIGHTDATA;
	if (s == "dpchengbrlyttbdata") return DPCHENGBRLYTTBDATA;
	if (s == "dpchengbrlyttbdetaildata") return DPCHENGBRLYTTBDETAILDATA;
	if (s == "dpchengbrlyttbheadbardata") return DPCHENGBRLYTTBHEADBARDATA;
	if (s == "dpchengbrlyttblistdata") return DPCHENGBRLYTTBLISTDATA;
	if (s == "dpchengbrlyttbrecdata") return DPCHENGBRLYTTBRECDATA;
	if (s == "dpchengbrlyttbref1nfiledata") return DPCHENGBRLYTTBREF1NFILEDATA;
	if (s == "dpchengbrlyusgaaccessdata") return DPCHENGBRLYUSGAACCESSDATA;
	if (s == "dpchengbrlyusgdata") return DPCHENGBRLYUSGDATA;
	if (s == "dpchengbrlyusgdetaildata") return DPCHENGBRLYUSGDETAILDATA;
	if (s == "dpchengbrlyusgheadbardata") return DPCHENGBRLYUSGHEADBARDATA;
	if (s == "dpchengbrlyusglistdata") return DPCHENGBRLYUSGLISTDATA;
	if (s == "dpchengbrlyusgmnuserdata") return DPCHENGBRLYUSGMNUSERDATA;
	if (s == "dpchengbrlyusgrecdata") return DPCHENGBRLYUSGRECDATA;
	if (s == "dpchengbrlyusr1nsessiondata") return DPCHENGBRLYUSR1NSESSIONDATA;
	if (s == "dpchengbrlyusraaccessdata") return DPCHENGBRLYUSRAACCESSDATA;
	if (s == "dpchengbrlyusrdata") return DPCHENGBRLYUSRDATA;
	if (s == "dpchengbrlyusrdetaildata") return DPCHENGBRLYUSRDETAILDATA;
	if (s == "dpchengbrlyusrheadbardata") return DPCHENGBRLYUSRHEADBARDATA;
	if (s == "dpchengbrlyusrlistdata") return DPCHENGBRLYUSRLISTDATA;
	if (s == "dpchengbrlyusrmnusergroupdata") return DPCHENGBRLYUSRMNUSERGROUPDATA;
	if (s == "dpchengbrlyusrrecdata") return DPCHENGBRLYUSRRECDATA;
	if (s == "dpchengdlgbrlyconnewdata") return DPCHENGDLGBRLYCONNEWDATA;
	if (s == "dpchengdlgbrlylegnewdata") return DPCHENGDLGBRLYLEGNEWDATA;
	if (s == "dpchengdlgbrlynavloainidata") return DPCHENGDLGBRLYNAVLOAINIDATA;
	if (s == "dpchengdlgbrlyttbimpfltdata") return DPCHENGDLGBRLYTTBIMPFLTDATA;
	if (s == "dpchengdlgbrlyttbnewdata") return DPCHENGDLGBRLYTTBNEWDATA;
	if (s == "dpchengdlgbrlyttbtrlorigdata") return DPCHENGDLGBRLYTTBTRLORIGDATA;
	if (s == "dpchengrootbrlydata") return DPCHENGROOTBRLYDATA;
	if (s == "dpchengsessbrlydata") return DPCHENGSESSBRLYDATA;
	if (s == "dpchinvbrly") return DPCHINVBRLY;
	if (s == "dpchinvbrlybaselegleg") return DPCHINVBRLYBASELEGLEG;
	if (s == "dpchinvbrlybaselegloc") return DPCHINVBRLYBASELEGLOC;
	if (s == "dpchinvbrlybaselocloc") return DPCHINVBRLYBASELOCLOC;
	if (s == "dpchinvbrlydnsmapcollect") return DPCHINVBRLYDNSMAPCOLLECT;
	if (s == "dpchinvbrlydnsmapframe") return DPCHINVBRLYDNSMAPFRAME;
	if (s == "dpchinvbrlydnsmapvideo") return DPCHINVBRLYDNSMAPVIDEO;
	if (s == "dpchinvbrlydynconflt") return DPCHINVBRLYDYNCONFLT;
	if (s == "dpchinvbrlydynconseg") return DPCHINVBRLYDYNCONSEG;
	if (s == "dpchinvbrlydyneqplist") return DPCHINVBRLYDYNEQPLIST;
	if (s == "dpchinvbrlydynfltfltloc") return DPCHINVBRLYDYNFLTFLTLOC;
	if (s == "dpchinvbrlydynfltseg") return DPCHINVBRLYDYNFLTSEG;
	if (s == "dpchinvbrlydynrly") return DPCHINVBRLYDYNRLY;
	if (s == "dpchinvbrlydynseglocseg") return DPCHINVBRLYDYNSEGLOCSEG;
	if (s == "dpchinvbrlymapgenconmap") return DPCHINVBRLYMAPGENCONMAP;
	if (s == "dpchinvbrlymapgenlegmap") return DPCHINVBRLYMAPGENLEGMAP;
	if (s == "dpchinvbrlymapgenlocmap") return DPCHINVBRLYMAPGENLOCMAP;
	if (s == "dpchinvbrlyttimprawstar") return DPCHINVBRLYTTIMPRAWSTAR;
	if (s == "dpchretbrly") return DPCHRETBRLY;
	if (s == "dpchretbrlydnsmapcollect") return DPCHRETBRLYDNSMAPCOLLECT;
	if (s == "dpchretbrlydnsmapframe") return DPCHRETBRLYDNSMAPFRAME;
	if (s == "dpchretbrlydnsmapvideo") return DPCHRETBRLYDNSMAPVIDEO;

	return(0);
};

string VecBrlyVDpch::getSref(
			const uint ix
		) {
	if (ix == DPCHAPPBRLYALERT) return("DpchAppBrlyAlert");
	if (ix == DPCHAPPBRLYCON1NRELAYDATA) return("DpchAppBrlyCon1NRelayData");
	if (ix == DPCHAPPBRLYCON1NRELAYDO) return("DpchAppBrlyCon1NRelayDo");
	if (ix == DPCHAPPBRLYCONCONMNEQUIPMENTDATA) return("DpchAppBrlyConConMNEquipmentData");
	if (ix == DPCHAPPBRLYCONCONMNEQUIPMENTDO) return("DpchAppBrlyConConMNEquipmentDo");
	if (ix == DPCHAPPBRLYCONDETAILDATA) return("DpchAppBrlyConDetailData");
	if (ix == DPCHAPPBRLYCONDETAILDO) return("DpchAppBrlyConDetailDo");
	if (ix == DPCHAPPBRLYCONDO) return("DpchAppBrlyConDo");
	if (ix == DPCHAPPBRLYCONLISTDATA) return("DpchAppBrlyConListData");
	if (ix == DPCHAPPBRLYCONLISTDO) return("DpchAppBrlyConListDo");
	if (ix == DPCHAPPBRLYCONMAPDATA) return("DpchAppBrlyConMapData");
	if (ix == DPCHAPPBRLYCONMAPDO) return("DpchAppBrlyConMapDo");
	if (ix == DPCHAPPBRLYCONMNFLIGHTDATA) return("DpchAppBrlyConMNFlightData");
	if (ix == DPCHAPPBRLYCONMNFLIGHTDO) return("DpchAppBrlyConMNFlightDo");
	if (ix == DPCHAPPBRLYCONMNSEGMENTDATA) return("DpchAppBrlyConMNSegmentData");
	if (ix == DPCHAPPBRLYCONMNSEGMENTDO) return("DpchAppBrlyConMNSegmentDo");
	if (ix == DPCHAPPBRLYCONPREDATA) return("DpchAppBrlyConPreData");
	if (ix == DPCHAPPBRLYCONRECDO) return("DpchAppBrlyConRecDo");
	if (ix == DPCHAPPBRLYCONREF1NSEGMENTDATA) return("DpchAppBrlyConRef1NSegmentData");
	if (ix == DPCHAPPBRLYCONREF1NSEGMENTDO) return("DpchAppBrlyConRef1NSegmentDo");
	if (ix == DPCHAPPBRLYFILDETAILDATA) return("DpchAppBrlyFilDetailData");
	if (ix == DPCHAPPBRLYFILDETAILDO) return("DpchAppBrlyFilDetailDo");
	if (ix == DPCHAPPBRLYFILDO) return("DpchAppBrlyFilDo");
	if (ix == DPCHAPPBRLYFILLISTDATA) return("DpchAppBrlyFilListData");
	if (ix == DPCHAPPBRLYFILLISTDO) return("DpchAppBrlyFilListDo");
	if (ix == DPCHAPPBRLYFILRECDO) return("DpchAppBrlyFilRecDo");
	if (ix == DPCHAPPBRLYFLT1NCONNECTIONDATA) return("DpchAppBrlyFlt1NConnectionData");
	if (ix == DPCHAPPBRLYFLT1NCONNECTIONDO) return("DpchAppBrlyFlt1NConnectionDo");
	if (ix == DPCHAPPBRLYFLTDETAILDATA) return("DpchAppBrlyFltDetailData");
	if (ix == DPCHAPPBRLYFLTDETAILDO) return("DpchAppBrlyFltDetailDo");
	if (ix == DPCHAPPBRLYFLTDO) return("DpchAppBrlyFltDo");
	if (ix == DPCHAPPBRLYFLTEQP1NNODEDATA) return("DpchAppBrlyFltEqp1NNodeData");
	if (ix == DPCHAPPBRLYFLTEQP1NNODEDO) return("DpchAppBrlyFltEqp1NNodeDo");
	if (ix == DPCHAPPBRLYFLTEQPMNCONNECTIONDATA) return("DpchAppBrlyFltEqpMNConnectionData");
	if (ix == DPCHAPPBRLYFLTEQPMNCONNECTIONDO) return("DpchAppBrlyFltEqpMNConnectionDo");
	if (ix == DPCHAPPBRLYFLTFAFAWAYPOINTDATA) return("DpchAppBrlyFltFafAWaypointData");
	if (ix == DPCHAPPBRLYFLTFAFAWAYPOINTDO) return("DpchAppBrlyFltFafAWaypointDo");
	if (ix == DPCHAPPBRLYFLTLISTDATA) return("DpchAppBrlyFltListData");
	if (ix == DPCHAPPBRLYFLTLISTDO) return("DpchAppBrlyFltListDo");
	if (ix == DPCHAPPBRLYFLTMNCONNECTIONDATA) return("DpchAppBrlyFltMNConnectionData");
	if (ix == DPCHAPPBRLYFLTMNCONNECTIONDO) return("DpchAppBrlyFltMNConnectionDo");
	if (ix == DPCHAPPBRLYFLTMNLOCATIONDATA) return("DpchAppBrlyFltMNLocationData");
	if (ix == DPCHAPPBRLYFLTMNLOCATIONDO) return("DpchAppBrlyFltMNLocationDo");
	if (ix == DPCHAPPBRLYFLTORGMNFLIGHTDATA) return("DpchAppBrlyFltOrgMNFlightData");
	if (ix == DPCHAPPBRLYFLTORGMNFLIGHTDO) return("DpchAppBrlyFltOrgMNFlightDo");
	if (ix == DPCHAPPBRLYFLTPREDATA) return("DpchAppBrlyFltPreData");
	if (ix == DPCHAPPBRLYFLTRECDO) return("DpchAppBrlyFltRecDo");
	if (ix == DPCHAPPBRLYFLTREF1NSEGMENTDATA) return("DpchAppBrlyFltRef1NSegmentData");
	if (ix == DPCHAPPBRLYFLTREF1NSEGMENTDO) return("DpchAppBrlyFltRef1NSegmentDo");
	if (ix == DPCHAPPBRLYINIT) return("DpchAppBrlyInit");
	if (ix == DPCHAPPBRLYLEG1NFLIGHTDATA) return("DpchAppBrlyLeg1NFlightData");
	if (ix == DPCHAPPBRLYLEG1NFLIGHTDO) return("DpchAppBrlyLeg1NFlightDo");
	if (ix == DPCHAPPBRLYLEGCOR1NCONNECTIONDATA) return("DpchAppBrlyLegCor1NConnectionData");
	if (ix == DPCHAPPBRLYLEGCOR1NCONNECTIONDO) return("DpchAppBrlyLegCor1NConnectionDo");
	if (ix == DPCHAPPBRLYLEGDETAILDATA) return("DpchAppBrlyLegDetailData");
	if (ix == DPCHAPPBRLYLEGDETAILDO) return("DpchAppBrlyLegDetailDo");
	if (ix == DPCHAPPBRLYLEGDO) return("DpchAppBrlyLegDo");
	if (ix == DPCHAPPBRLYLEGLISTDATA) return("DpchAppBrlyLegListData");
	if (ix == DPCHAPPBRLYLEGLISTDO) return("DpchAppBrlyLegListDo");
	if (ix == DPCHAPPBRLYLEGMAPDATA) return("DpchAppBrlyLegMapData");
	if (ix == DPCHAPPBRLYLEGMAPDO) return("DpchAppBrlyLegMapDo");
	if (ix == DPCHAPPBRLYLEGMNLOCATIONDATA) return("DpchAppBrlyLegMNLocationData");
	if (ix == DPCHAPPBRLYLEGMNLOCATIONDO) return("DpchAppBrlyLegMNLocationDo");
	if (ix == DPCHAPPBRLYLEGORGMNLEGDATA) return("DpchAppBrlyLegOrgMNLegData");
	if (ix == DPCHAPPBRLYLEGORGMNLEGDO) return("DpchAppBrlyLegOrgMNLegDo");
	if (ix == DPCHAPPBRLYLEGPREDATA) return("DpchAppBrlyLegPreData");
	if (ix == DPCHAPPBRLYLEGRECDO) return("DpchAppBrlyLegRecDo");
	if (ix == DPCHAPPBRLYLOCBGN1NLEGDATA) return("DpchAppBrlyLocBgn1NLegData");
	if (ix == DPCHAPPBRLYLOCBGN1NLEGDO) return("DpchAppBrlyLocBgn1NLegDo");
	if (ix == DPCHAPPBRLYLOCDETAILDATA) return("DpchAppBrlyLocDetailData");
	if (ix == DPCHAPPBRLYLOCDETAILDO) return("DpchAppBrlyLocDetailDo");
	if (ix == DPCHAPPBRLYLOCDO) return("DpchAppBrlyLocDo");
	if (ix == DPCHAPPBRLYLOCEND1NLEGDATA) return("DpchAppBrlyLocEnd1NLegData");
	if (ix == DPCHAPPBRLYLOCEND1NLEGDO) return("DpchAppBrlyLocEnd1NLegDo");
	if (ix == DPCHAPPBRLYLOCEQP1NNODEDATA) return("DpchAppBrlyLocEqp1NNodeData");
	if (ix == DPCHAPPBRLYLOCEQP1NNODEDO) return("DpchAppBrlyLocEqp1NNodeDo");
	if (ix == DPCHAPPBRLYLOCEQPMNCONNECTIONDATA) return("DpchAppBrlyLocEqpMNConnectionData");
	if (ix == DPCHAPPBRLYLOCEQPMNCONNECTIONDO) return("DpchAppBrlyLocEqpMNConnectionDo");
	if (ix == DPCHAPPBRLYLOCLISTDATA) return("DpchAppBrlyLocListData");
	if (ix == DPCHAPPBRLYLOCLISTDO) return("DpchAppBrlyLocListDo");
	if (ix == DPCHAPPBRLYLOCMAPDATA) return("DpchAppBrlyLocMapData");
	if (ix == DPCHAPPBRLYLOCMAPDO) return("DpchAppBrlyLocMapDo");
	if (ix == DPCHAPPBRLYLOCMNFLIGHTDATA) return("DpchAppBrlyLocMNFlightData");
	if (ix == DPCHAPPBRLYLOCMNFLIGHTDO) return("DpchAppBrlyLocMNFlightDo");
	if (ix == DPCHAPPBRLYLOCMNLEGDATA) return("DpchAppBrlyLocMNLegData");
	if (ix == DPCHAPPBRLYLOCMNLEGDO) return("DpchAppBrlyLocMNLegDo");
	if (ix == DPCHAPPBRLYLOCMNSEGMENTDATA) return("DpchAppBrlyLocMNSegmentData");
	if (ix == DPCHAPPBRLYLOCMNSEGMENTDO) return("DpchAppBrlyLocMNSegmentDo");
	if (ix == DPCHAPPBRLYLOCPROXORGMNLOCATIONDATA) return("DpchAppBrlyLocProxOrgMNLocationData");
	if (ix == DPCHAPPBRLYLOCPROXORGMNLOCATIONDO) return("DpchAppBrlyLocProxOrgMNLocationDo");
	if (ix == DPCHAPPBRLYLOCRECDO) return("DpchAppBrlyLocRecDo");
	if (ix == DPCHAPPBRLYLOCVISORGMNLOCATIONDATA) return("DpchAppBrlyLocVisOrgMNLocationData");
	if (ix == DPCHAPPBRLYLOCVISORGMNLOCATIONDO) return("DpchAppBrlyLocVisOrgMNLocationDo");
	if (ix == DPCHAPPBRLYNAVADMINDATA) return("DpchAppBrlyNavAdminData");
	if (ix == DPCHAPPBRLYNAVADMINDO) return("DpchAppBrlyNavAdminDo");
	if (ix == DPCHAPPBRLYNAVBASEDATA) return("DpchAppBrlyNavBaseData");
	if (ix == DPCHAPPBRLYNAVBASEDO) return("DpchAppBrlyNavBaseDo");
	if (ix == DPCHAPPBRLYNAVCONNECTDATA) return("DpchAppBrlyNavConnectData");
	if (ix == DPCHAPPBRLYNAVCONNECTDO) return("DpchAppBrlyNavConnectDo");
	if (ix == DPCHAPPBRLYNAVDO) return("DpchAppBrlyNavDo");
	if (ix == DPCHAPPBRLYOPR1NEQUIPMENTDATA) return("DpchAppBrlyOpr1NEquipmentData");
	if (ix == DPCHAPPBRLYOPR1NEQUIPMENTDO) return("DpchAppBrlyOpr1NEquipmentDo");
	if (ix == DPCHAPPBRLYOPRDETAILDATA) return("DpchAppBrlyOprDetailData");
	if (ix == DPCHAPPBRLYOPRDETAILDO) return("DpchAppBrlyOprDetailDo");
	if (ix == DPCHAPPBRLYOPRDO) return("DpchAppBrlyOprDo");
	if (ix == DPCHAPPBRLYOPRLISTDATA) return("DpchAppBrlyOprListData");
	if (ix == DPCHAPPBRLYOPRLISTDO) return("DpchAppBrlyOprListDo");
	if (ix == DPCHAPPBRLYOPRRECDO) return("DpchAppBrlyOprRecDo");
	if (ix == DPCHAPPBRLYPRSADETAILDATA) return("DpchAppBrlyPrsADetailData");
	if (ix == DPCHAPPBRLYPRSADETAILDO) return("DpchAppBrlyPrsADetailDo");
	if (ix == DPCHAPPBRLYPRSDETAILDATA) return("DpchAppBrlyPrsDetailData");
	if (ix == DPCHAPPBRLYPRSDETAILDO) return("DpchAppBrlyPrsDetailDo");
	if (ix == DPCHAPPBRLYPRSDO) return("DpchAppBrlyPrsDo");
	if (ix == DPCHAPPBRLYPRSLISTDATA) return("DpchAppBrlyPrsListData");
	if (ix == DPCHAPPBRLYPRSLISTDO) return("DpchAppBrlyPrsListDo");
	if (ix == DPCHAPPBRLYPRSRECDO) return("DpchAppBrlyPrsRecDo");
	if (ix == DPCHAPPBRLYPTY1NEQUIPMENTDATA) return("DpchAppBrlyPty1NEquipmentData");
	if (ix == DPCHAPPBRLYPTY1NEQUIPMENTDO) return("DpchAppBrlyPty1NEquipmentDo");
	if (ix == DPCHAPPBRLYPTYDETAILDATA) return("DpchAppBrlyPtyDetailData");
	if (ix == DPCHAPPBRLYPTYDETAILDO) return("DpchAppBrlyPtyDetailDo");
	if (ix == DPCHAPPBRLYPTYDO) return("DpchAppBrlyPtyDo");
	if (ix == DPCHAPPBRLYPTYLISTDATA) return("DpchAppBrlyPtyListData");
	if (ix == DPCHAPPBRLYPTYLISTDO) return("DpchAppBrlyPtyListDo");
	if (ix == DPCHAPPBRLYPTYRECDO) return("DpchAppBrlyPtyRecDo");
	if (ix == DPCHAPPBRLYREG1NLOCATIONDATA) return("DpchAppBrlyReg1NLocationData");
	if (ix == DPCHAPPBRLYREG1NLOCATIONDO) return("DpchAppBrlyReg1NLocationDo");
	if (ix == DPCHAPPBRLYREGADSTSWITCHDATA) return("DpchAppBrlyRegADstswitchData");
	if (ix == DPCHAPPBRLYREGADSTSWITCHDO) return("DpchAppBrlyRegADstswitchDo");
	if (ix == DPCHAPPBRLYREGDETAILDATA) return("DpchAppBrlyRegDetailData");
	if (ix == DPCHAPPBRLYREGDETAILDO) return("DpchAppBrlyRegDetailDo");
	if (ix == DPCHAPPBRLYREGDO) return("DpchAppBrlyRegDo");
	if (ix == DPCHAPPBRLYREGLISTDATA) return("DpchAppBrlyRegListData");
	if (ix == DPCHAPPBRLYREGLISTDO) return("DpchAppBrlyRegListDo");
	if (ix == DPCHAPPBRLYREGRECDO) return("DpchAppBrlyRegRecDo");
	if (ix == DPCHAPPBRLYREGSUP1NREGIONDATA) return("DpchAppBrlyRegSup1NRegionData");
	if (ix == DPCHAPPBRLYREGSUP1NREGIONDO) return("DpchAppBrlyRegSup1NRegionDo");
	if (ix == DPCHAPPBRLYRESUME) return("DpchAppBrlyResume");
	if (ix == DPCHAPPBRLYRLY1NNODEDATA) return("DpchAppBrlyRly1NNodeData");
	if (ix == DPCHAPPBRLYRLY1NNODEDO) return("DpchAppBrlyRly1NNodeDo");
	if (ix == DPCHAPPBRLYRLYDETAILDATA) return("DpchAppBrlyRlyDetailData");
	if (ix == DPCHAPPBRLYRLYDETAILDO) return("DpchAppBrlyRlyDetailDo");
	if (ix == DPCHAPPBRLYRLYDO) return("DpchAppBrlyRlyDo");
	if (ix == DPCHAPPBRLYRLYLISTDATA) return("DpchAppBrlyRlyListData");
	if (ix == DPCHAPPBRLYRLYLISTDO) return("DpchAppBrlyRlyListDo");
	if (ix == DPCHAPPBRLYRLYRECDO) return("DpchAppBrlyRlyRecDo");
	if (ix == DPCHAPPBRLYSEGDETAILDATA) return("DpchAppBrlySegDetailData");
	if (ix == DPCHAPPBRLYSEGDETAILDO) return("DpchAppBrlySegDetailDo");
	if (ix == DPCHAPPBRLYSEGDO) return("DpchAppBrlySegDo");
	if (ix == DPCHAPPBRLYSEGLISTDATA) return("DpchAppBrlySegListData");
	if (ix == DPCHAPPBRLYSEGLISTDO) return("DpchAppBrlySegListDo");
	if (ix == DPCHAPPBRLYSEGMNCONNECTIONDATA) return("DpchAppBrlySegMNConnectionData");
	if (ix == DPCHAPPBRLYSEGMNCONNECTIONDO) return("DpchAppBrlySegMNConnectionDo");
	if (ix == DPCHAPPBRLYSEGMNLOCATIONDATA) return("DpchAppBrlySegMNLocationData");
	if (ix == DPCHAPPBRLYSEGMNLOCATIONDO) return("DpchAppBrlySegMNLocationDo");
	if (ix == DPCHAPPBRLYSEGORGMNSEGMENTDATA) return("DpchAppBrlySegOrgMNSegmentData");
	if (ix == DPCHAPPBRLYSEGORGMNSEGMENTDO) return("DpchAppBrlySegOrgMNSegmentDo");
	if (ix == DPCHAPPBRLYSEGPREDATA) return("DpchAppBrlySegPreData");
	if (ix == DPCHAPPBRLYSEGRECDO) return("DpchAppBrlySegRecDo");
	if (ix == DPCHAPPBRLYTTB1NFLIGHTDATA) return("DpchAppBrlyTtb1NFlightData");
	if (ix == DPCHAPPBRLYTTB1NFLIGHTDO) return("DpchAppBrlyTtb1NFlightDo");
	if (ix == DPCHAPPBRLYTTBDETAILDATA) return("DpchAppBrlyTtbDetailData");
	if (ix == DPCHAPPBRLYTTBDETAILDO) return("DpchAppBrlyTtbDetailDo");
	if (ix == DPCHAPPBRLYTTBDO) return("DpchAppBrlyTtbDo");
	if (ix == DPCHAPPBRLYTTBLISTDATA) return("DpchAppBrlyTtbListData");
	if (ix == DPCHAPPBRLYTTBLISTDO) return("DpchAppBrlyTtbListDo");
	if (ix == DPCHAPPBRLYTTBRECDO) return("DpchAppBrlyTtbRecDo");
	if (ix == DPCHAPPBRLYTTBREF1NFILEDATA) return("DpchAppBrlyTtbRef1NFileData");
	if (ix == DPCHAPPBRLYTTBREF1NFILEDO) return("DpchAppBrlyTtbRef1NFileDo");
	if (ix == DPCHAPPBRLYUSGAACCESSDATA) return("DpchAppBrlyUsgAAccessData");
	if (ix == DPCHAPPBRLYUSGAACCESSDO) return("DpchAppBrlyUsgAAccessDo");
	if (ix == DPCHAPPBRLYUSGDETAILDATA) return("DpchAppBrlyUsgDetailData");
	if (ix == DPCHAPPBRLYUSGDETAILDO) return("DpchAppBrlyUsgDetailDo");
	if (ix == DPCHAPPBRLYUSGDO) return("DpchAppBrlyUsgDo");
	if (ix == DPCHAPPBRLYUSGLISTDATA) return("DpchAppBrlyUsgListData");
	if (ix == DPCHAPPBRLYUSGLISTDO) return("DpchAppBrlyUsgListDo");
	if (ix == DPCHAPPBRLYUSGMNUSERDATA) return("DpchAppBrlyUsgMNUserData");
	if (ix == DPCHAPPBRLYUSGMNUSERDO) return("DpchAppBrlyUsgMNUserDo");
	if (ix == DPCHAPPBRLYUSGRECDO) return("DpchAppBrlyUsgRecDo");
	if (ix == DPCHAPPBRLYUSR1NSESSIONDATA) return("DpchAppBrlyUsr1NSessionData");
	if (ix == DPCHAPPBRLYUSR1NSESSIONDO) return("DpchAppBrlyUsr1NSessionDo");
	if (ix == DPCHAPPBRLYUSRAACCESSDATA) return("DpchAppBrlyUsrAAccessData");
	if (ix == DPCHAPPBRLYUSRAACCESSDO) return("DpchAppBrlyUsrAAccessDo");
	if (ix == DPCHAPPBRLYUSRDETAILDATA) return("DpchAppBrlyUsrDetailData");
	if (ix == DPCHAPPBRLYUSRDETAILDO) return("DpchAppBrlyUsrDetailDo");
	if (ix == DPCHAPPBRLYUSRDO) return("DpchAppBrlyUsrDo");
	if (ix == DPCHAPPBRLYUSRLISTDATA) return("DpchAppBrlyUsrListData");
	if (ix == DPCHAPPBRLYUSRLISTDO) return("DpchAppBrlyUsrListDo");
	if (ix == DPCHAPPBRLYUSRMNUSERGROUPDATA) return("DpchAppBrlyUsrMNUsergroupData");
	if (ix == DPCHAPPBRLYUSRMNUSERGROUPDO) return("DpchAppBrlyUsrMNUsergroupDo");
	if (ix == DPCHAPPBRLYUSRRECDO) return("DpchAppBrlyUsrRecDo");
	if (ix == DPCHAPPDLGBRLYCONNEWDATA) return("DpchAppDlgBrlyConNewData");
	if (ix == DPCHAPPDLGBRLYCONNEWDO) return("DpchAppDlgBrlyConNewDo");
	if (ix == DPCHAPPDLGBRLYLEGNEWDATA) return("DpchAppDlgBrlyLegNewData");
	if (ix == DPCHAPPDLGBRLYLEGNEWDO) return("DpchAppDlgBrlyLegNewDo");
	if (ix == DPCHAPPDLGBRLYNAVLOAINIDATA) return("DpchAppDlgBrlyNavLoainiData");
	if (ix == DPCHAPPDLGBRLYNAVLOAINIDO) return("DpchAppDlgBrlyNavLoainiDo");
	if (ix == DPCHAPPDLGBRLYTTBIMPFLTDATA) return("DpchAppDlgBrlyTtbImpfltData");
	if (ix == DPCHAPPDLGBRLYTTBIMPFLTDO) return("DpchAppDlgBrlyTtbImpfltDo");
	if (ix == DPCHAPPDLGBRLYTTBNEWDATA) return("DpchAppDlgBrlyTtbNewData");
	if (ix == DPCHAPPDLGBRLYTTBNEWDO) return("DpchAppDlgBrlyTtbNewDo");
	if (ix == DPCHAPPDLGBRLYTTBTRLORIGDATA) return("DpchAppDlgBrlyTtbTrlorigData");
	if (ix == DPCHAPPDLGBRLYTTBTRLORIGDO) return("DpchAppDlgBrlyTtbTrlorigDo");
	if (ix == DPCHAPPROOTBRLYLOGIN) return("DpchAppRootBrlyLogin");
	if (ix == DPCHBRLYDACK) return("DpchBrlydAck");
	if (ix == DPCHBRLYDQUIT) return("DpchBrlydQuit");
	if (ix == DPCHBRLYDREG) return("DpchBrlydReg");
	if (ix == DPCHBRLYOPDREG) return("DpchBrlyopdReg");
	if (ix == DPCHBRLYOPDUNREG) return("DpchBrlyopdUnreg");
	if (ix == DPCHENGBRLYACK) return("DpchEngBrlyAck");
	if (ix == DPCHENGBRLYALERT) return("DpchEngBrlyAlert");
	if (ix == DPCHENGBRLYCON1NRELAYDATA) return("DpchEngBrlyCon1NRelayData");
	if (ix == DPCHENGBRLYCONCONMNEQUIPMENTDATA) return("DpchEngBrlyConConMNEquipmentData");
	if (ix == DPCHENGBRLYCONDATA) return("DpchEngBrlyConData");
	if (ix == DPCHENGBRLYCONDETAILDATA) return("DpchEngBrlyConDetailData");
	if (ix == DPCHENGBRLYCONFIRM) return("DpchEngBrlyConfirm");
	if (ix == DPCHENGBRLYCONHEADBARDATA) return("DpchEngBrlyConHeadbarData");
	if (ix == DPCHENGBRLYCONLISTDATA) return("DpchEngBrlyConListData");
	if (ix == DPCHENGBRLYCONMAPDATA) return("DpchEngBrlyConMapData");
	if (ix == DPCHENGBRLYCONMAPIMAGE) return("DpchEngBrlyConMapImage");
	if (ix == DPCHENGBRLYCONMNFLIGHTDATA) return("DpchEngBrlyConMNFlightData");
	if (ix == DPCHENGBRLYCONMNSEGMENTDATA) return("DpchEngBrlyConMNSegmentData");
	if (ix == DPCHENGBRLYCONPREDATA) return("DpchEngBrlyConPreData");
	if (ix == DPCHENGBRLYCONRECDATA) return("DpchEngBrlyConRecData");
	if (ix == DPCHENGBRLYCONREF1NSEGMENTDATA) return("DpchEngBrlyConRef1NSegmentData");
	if (ix == DPCHENGBRLYFILDATA) return("DpchEngBrlyFilData");
	if (ix == DPCHENGBRLYFILDETAILDATA) return("DpchEngBrlyFilDetailData");
	if (ix == DPCHENGBRLYFILHEADBARDATA) return("DpchEngBrlyFilHeadbarData");
	if (ix == DPCHENGBRLYFILLISTDATA) return("DpchEngBrlyFilListData");
	if (ix == DPCHENGBRLYFILRECDATA) return("DpchEngBrlyFilRecData");
	if (ix == DPCHENGBRLYFLT1NCONNECTIONDATA) return("DpchEngBrlyFlt1NConnectionData");
	if (ix == DPCHENGBRLYFLTDATA) return("DpchEngBrlyFltData");
	if (ix == DPCHENGBRLYFLTDETAILDATA) return("DpchEngBrlyFltDetailData");
	if (ix == DPCHENGBRLYFLTEQP1NNODEDATA) return("DpchEngBrlyFltEqp1NNodeData");
	if (ix == DPCHENGBRLYFLTEQPMNCONNECTIONDATA) return("DpchEngBrlyFltEqpMNConnectionData");
	if (ix == DPCHENGBRLYFLTFAFAWAYPOINTDATA) return("DpchEngBrlyFltFafAWaypointData");
	if (ix == DPCHENGBRLYFLTHEADBARDATA) return("DpchEngBrlyFltHeadbarData");
	if (ix == DPCHENGBRLYFLTLISTDATA) return("DpchEngBrlyFltListData");
	if (ix == DPCHENGBRLYFLTMNCONNECTIONDATA) return("DpchEngBrlyFltMNConnectionData");
	if (ix == DPCHENGBRLYFLTMNLOCATIONDATA) return("DpchEngBrlyFltMNLocationData");
	if (ix == DPCHENGBRLYFLTORGMNFLIGHTDATA) return("DpchEngBrlyFltOrgMNFlightData");
	if (ix == DPCHENGBRLYFLTPREDATA) return("DpchEngBrlyFltPreData");
	if (ix == DPCHENGBRLYFLTRECDATA) return("DpchEngBrlyFltRecData");
	if (ix == DPCHENGBRLYFLTREF1NSEGMENTDATA) return("DpchEngBrlyFltRef1NSegmentData");
	if (ix == DPCHENGBRLYLEG1NFLIGHTDATA) return("DpchEngBrlyLeg1NFlightData");
	if (ix == DPCHENGBRLYLEGCOR1NCONNECTIONDATA) return("DpchEngBrlyLegCor1NConnectionData");
	if (ix == DPCHENGBRLYLEGDATA) return("DpchEngBrlyLegData");
	if (ix == DPCHENGBRLYLEGDETAILDATA) return("DpchEngBrlyLegDetailData");
	if (ix == DPCHENGBRLYLEGHEADBARDATA) return("DpchEngBrlyLegHeadbarData");
	if (ix == DPCHENGBRLYLEGLISTDATA) return("DpchEngBrlyLegListData");
	if (ix == DPCHENGBRLYLEGMAPDATA) return("DpchEngBrlyLegMapData");
	if (ix == DPCHENGBRLYLEGMAPIMAGE) return("DpchEngBrlyLegMapImage");
	if (ix == DPCHENGBRLYLEGMNLOCATIONDATA) return("DpchEngBrlyLegMNLocationData");
	if (ix == DPCHENGBRLYLEGORGMNLEGDATA) return("DpchEngBrlyLegOrgMNLegData");
	if (ix == DPCHENGBRLYLEGPREDATA) return("DpchEngBrlyLegPreData");
	if (ix == DPCHENGBRLYLEGRECDATA) return("DpchEngBrlyLegRecData");
	if (ix == DPCHENGBRLYLOCBGN1NLEGDATA) return("DpchEngBrlyLocBgn1NLegData");
	if (ix == DPCHENGBRLYLOCDATA) return("DpchEngBrlyLocData");
	if (ix == DPCHENGBRLYLOCDETAILDATA) return("DpchEngBrlyLocDetailData");
	if (ix == DPCHENGBRLYLOCEND1NLEGDATA) return("DpchEngBrlyLocEnd1NLegData");
	if (ix == DPCHENGBRLYLOCEQP1NNODEDATA) return("DpchEngBrlyLocEqp1NNodeData");
	if (ix == DPCHENGBRLYLOCEQPMNCONNECTIONDATA) return("DpchEngBrlyLocEqpMNConnectionData");
	if (ix == DPCHENGBRLYLOCHEADBARDATA) return("DpchEngBrlyLocHeadbarData");
	if (ix == DPCHENGBRLYLOCLISTDATA) return("DpchEngBrlyLocListData");
	if (ix == DPCHENGBRLYLOCMAPDATA) return("DpchEngBrlyLocMapData");
	if (ix == DPCHENGBRLYLOCMAPIMAGE) return("DpchEngBrlyLocMapImage");
	if (ix == DPCHENGBRLYLOCMNFLIGHTDATA) return("DpchEngBrlyLocMNFlightData");
	if (ix == DPCHENGBRLYLOCMNLEGDATA) return("DpchEngBrlyLocMNLegData");
	if (ix == DPCHENGBRLYLOCMNSEGMENTDATA) return("DpchEngBrlyLocMNSegmentData");
	if (ix == DPCHENGBRLYLOCPROXORGMNLOCATIONDATA) return("DpchEngBrlyLocProxOrgMNLocationData");
	if (ix == DPCHENGBRLYLOCRECDATA) return("DpchEngBrlyLocRecData");
	if (ix == DPCHENGBRLYLOCVISORGMNLOCATIONDATA) return("DpchEngBrlyLocVisOrgMNLocationData");
	if (ix == DPCHENGBRLYNAVADMINDATA) return("DpchEngBrlyNavAdminData");
	if (ix == DPCHENGBRLYNAVBASEDATA) return("DpchEngBrlyNavBaseData");
	if (ix == DPCHENGBRLYNAVCONNECTDATA) return("DpchEngBrlyNavConnectData");
	if (ix == DPCHENGBRLYNAVDATA) return("DpchEngBrlyNavData");
	if (ix == DPCHENGBRLYNAVHEADBARDATA) return("DpchEngBrlyNavHeadbarData");
	if (ix == DPCHENGBRLYOPR1NEQUIPMENTDATA) return("DpchEngBrlyOpr1NEquipmentData");
	if (ix == DPCHENGBRLYOPRDATA) return("DpchEngBrlyOprData");
	if (ix == DPCHENGBRLYOPRDETAILDATA) return("DpchEngBrlyOprDetailData");
	if (ix == DPCHENGBRLYOPRHEADBARDATA) return("DpchEngBrlyOprHeadbarData");
	if (ix == DPCHENGBRLYOPRLISTDATA) return("DpchEngBrlyOprListData");
	if (ix == DPCHENGBRLYOPRRECDATA) return("DpchEngBrlyOprRecData");
	if (ix == DPCHENGBRLYPRSADETAILDATA) return("DpchEngBrlyPrsADetailData");
	if (ix == DPCHENGBRLYPRSDATA) return("DpchEngBrlyPrsData");
	if (ix == DPCHENGBRLYPRSDETAILDATA) return("DpchEngBrlyPrsDetailData");
	if (ix == DPCHENGBRLYPRSHEADBARDATA) return("DpchEngBrlyPrsHeadbarData");
	if (ix == DPCHENGBRLYPRSLISTDATA) return("DpchEngBrlyPrsListData");
	if (ix == DPCHENGBRLYPRSRECDATA) return("DpchEngBrlyPrsRecData");
	if (ix == DPCHENGBRLYPTY1NEQUIPMENTDATA) return("DpchEngBrlyPty1NEquipmentData");
	if (ix == DPCHENGBRLYPTYDATA) return("DpchEngBrlyPtyData");
	if (ix == DPCHENGBRLYPTYDETAILDATA) return("DpchEngBrlyPtyDetailData");
	if (ix == DPCHENGBRLYPTYHEADBARDATA) return("DpchEngBrlyPtyHeadbarData");
	if (ix == DPCHENGBRLYPTYLISTDATA) return("DpchEngBrlyPtyListData");
	if (ix == DPCHENGBRLYPTYRECDATA) return("DpchEngBrlyPtyRecData");
	if (ix == DPCHENGBRLYREG1NLOCATIONDATA) return("DpchEngBrlyReg1NLocationData");
	if (ix == DPCHENGBRLYREGADSTSWITCHDATA) return("DpchEngBrlyRegADstswitchData");
	if (ix == DPCHENGBRLYREGDATA) return("DpchEngBrlyRegData");
	if (ix == DPCHENGBRLYREGDETAILDATA) return("DpchEngBrlyRegDetailData");
	if (ix == DPCHENGBRLYREGHEADBARDATA) return("DpchEngBrlyRegHeadbarData");
	if (ix == DPCHENGBRLYREGLISTDATA) return("DpchEngBrlyRegListData");
	if (ix == DPCHENGBRLYREGRECDATA) return("DpchEngBrlyRegRecData");
	if (ix == DPCHENGBRLYREGSUP1NREGIONDATA) return("DpchEngBrlyRegSup1NRegionData");
	if (ix == DPCHENGBRLYRLY1NNODEDATA) return("DpchEngBrlyRly1NNodeData");
	if (ix == DPCHENGBRLYRLYDATA) return("DpchEngBrlyRlyData");
	if (ix == DPCHENGBRLYRLYDETAILDATA) return("DpchEngBrlyRlyDetailData");
	if (ix == DPCHENGBRLYRLYHEADBARDATA) return("DpchEngBrlyRlyHeadbarData");
	if (ix == DPCHENGBRLYRLYLISTDATA) return("DpchEngBrlyRlyListData");
	if (ix == DPCHENGBRLYRLYRECDATA) return("DpchEngBrlyRlyRecData");
	if (ix == DPCHENGBRLYSEGDATA) return("DpchEngBrlySegData");
	if (ix == DPCHENGBRLYSEGDETAILDATA) return("DpchEngBrlySegDetailData");
	if (ix == DPCHENGBRLYSEGHEADBARDATA) return("DpchEngBrlySegHeadbarData");
	if (ix == DPCHENGBRLYSEGLISTDATA) return("DpchEngBrlySegListData");
	if (ix == DPCHENGBRLYSEGMNCONNECTIONDATA) return("DpchEngBrlySegMNConnectionData");
	if (ix == DPCHENGBRLYSEGMNLOCATIONDATA) return("DpchEngBrlySegMNLocationData");
	if (ix == DPCHENGBRLYSEGORGMNSEGMENTDATA) return("DpchEngBrlySegOrgMNSegmentData");
	if (ix == DPCHENGBRLYSEGPREDATA) return("DpchEngBrlySegPreData");
	if (ix == DPCHENGBRLYSEGRECDATA) return("DpchEngBrlySegRecData");
	if (ix == DPCHENGBRLYSUSPEND) return("DpchEngBrlySuspend");
	if (ix == DPCHENGBRLYTTB1NFLIGHTDATA) return("DpchEngBrlyTtb1NFlightData");
	if (ix == DPCHENGBRLYTTBDATA) return("DpchEngBrlyTtbData");
	if (ix == DPCHENGBRLYTTBDETAILDATA) return("DpchEngBrlyTtbDetailData");
	if (ix == DPCHENGBRLYTTBHEADBARDATA) return("DpchEngBrlyTtbHeadbarData");
	if (ix == DPCHENGBRLYTTBLISTDATA) return("DpchEngBrlyTtbListData");
	if (ix == DPCHENGBRLYTTBRECDATA) return("DpchEngBrlyTtbRecData");
	if (ix == DPCHENGBRLYTTBREF1NFILEDATA) return("DpchEngBrlyTtbRef1NFileData");
	if (ix == DPCHENGBRLYUSGAACCESSDATA) return("DpchEngBrlyUsgAAccessData");
	if (ix == DPCHENGBRLYUSGDATA) return("DpchEngBrlyUsgData");
	if (ix == DPCHENGBRLYUSGDETAILDATA) return("DpchEngBrlyUsgDetailData");
	if (ix == DPCHENGBRLYUSGHEADBARDATA) return("DpchEngBrlyUsgHeadbarData");
	if (ix == DPCHENGBRLYUSGLISTDATA) return("DpchEngBrlyUsgListData");
	if (ix == DPCHENGBRLYUSGMNUSERDATA) return("DpchEngBrlyUsgMNUserData");
	if (ix == DPCHENGBRLYUSGRECDATA) return("DpchEngBrlyUsgRecData");
	if (ix == DPCHENGBRLYUSR1NSESSIONDATA) return("DpchEngBrlyUsr1NSessionData");
	if (ix == DPCHENGBRLYUSRAACCESSDATA) return("DpchEngBrlyUsrAAccessData");
	if (ix == DPCHENGBRLYUSRDATA) return("DpchEngBrlyUsrData");
	if (ix == DPCHENGBRLYUSRDETAILDATA) return("DpchEngBrlyUsrDetailData");
	if (ix == DPCHENGBRLYUSRHEADBARDATA) return("DpchEngBrlyUsrHeadbarData");
	if (ix == DPCHENGBRLYUSRLISTDATA) return("DpchEngBrlyUsrListData");
	if (ix == DPCHENGBRLYUSRMNUSERGROUPDATA) return("DpchEngBrlyUsrMNUsergroupData");
	if (ix == DPCHENGBRLYUSRRECDATA) return("DpchEngBrlyUsrRecData");
	if (ix == DPCHENGDLGBRLYCONNEWDATA) return("DpchEngDlgBrlyConNewData");
	if (ix == DPCHENGDLGBRLYLEGNEWDATA) return("DpchEngDlgBrlyLegNewData");
	if (ix == DPCHENGDLGBRLYNAVLOAINIDATA) return("DpchEngDlgBrlyNavLoainiData");
	if (ix == DPCHENGDLGBRLYTTBIMPFLTDATA) return("DpchEngDlgBrlyTtbImpfltData");
	if (ix == DPCHENGDLGBRLYTTBNEWDATA) return("DpchEngDlgBrlyTtbNewData");
	if (ix == DPCHENGDLGBRLYTTBTRLORIGDATA) return("DpchEngDlgBrlyTtbTrlorigData");
	if (ix == DPCHENGROOTBRLYDATA) return("DpchEngRootBrlyData");
	if (ix == DPCHENGSESSBRLYDATA) return("DpchEngSessBrlyData");
	if (ix == DPCHINVBRLY) return("DpchInvBrly");
	if (ix == DPCHINVBRLYBASELEGLEG) return("DpchInvBrlyBaseLegleg");
	if (ix == DPCHINVBRLYBASELEGLOC) return("DpchInvBrlyBaseLegloc");
	if (ix == DPCHINVBRLYBASELOCLOC) return("DpchInvBrlyBaseLocloc");
	if (ix == DPCHINVBRLYDNSMAPCOLLECT) return("DpchInvBrlyDnsmapCollect");
	if (ix == DPCHINVBRLYDNSMAPFRAME) return("DpchInvBrlyDnsmapFrame");
	if (ix == DPCHINVBRLYDNSMAPVIDEO) return("DpchInvBrlyDnsmapVideo");
	if (ix == DPCHINVBRLYDYNCONFLT) return("DpchInvBrlyDynConflt");
	if (ix == DPCHINVBRLYDYNCONSEG) return("DpchInvBrlyDynConseg");
	if (ix == DPCHINVBRLYDYNEQPLIST) return("DpchInvBrlyDynEqplist");
	if (ix == DPCHINVBRLYDYNFLTFLTLOC) return("DpchInvBrlyDynFltfltloc");
	if (ix == DPCHINVBRLYDYNFLTSEG) return("DpchInvBrlyDynFltseg");
	if (ix == DPCHINVBRLYDYNRLY) return("DpchInvBrlyDynRly");
	if (ix == DPCHINVBRLYDYNSEGLOCSEG) return("DpchInvBrlyDynSeglocseg");
	if (ix == DPCHINVBRLYMAPGENCONMAP) return("DpchInvBrlyMapgenConmap");
	if (ix == DPCHINVBRLYMAPGENLEGMAP) return("DpchInvBrlyMapgenLegmap");
	if (ix == DPCHINVBRLYMAPGENLOCMAP) return("DpchInvBrlyMapgenLocmap");
	if (ix == DPCHINVBRLYTTIMPRAWSTAR) return("DpchInvBrlyTtimpRawstar");
	if (ix == DPCHRETBRLY) return("DpchRetBrly");
	if (ix == DPCHRETBRLYDNSMAPCOLLECT) return("DpchRetBrlyDnsmapCollect");
	if (ix == DPCHRETBRLYDNSMAPFRAME) return("DpchRetBrlyDnsmapFrame");
	if (ix == DPCHRETBRLYDNSMAPVIDEO) return("DpchRetBrlyDnsmapVideo");

	return("");
};
